package reflaxe.php.print;

import reflaxe.php.ir.PhpSourceRange;
import reflaxe.php.ir.PhpStableId;

/** Exact generated byte span paired with one authenticated source origin. **/
class PhpRenderedMapping {
	public final id:String;
	public final nodeKind:String;
	public final generatedStartByte:Int;
	public final generatedEndByte:Int;
	public final source:PhpSourceRange;
	public final semanticNodeId:String;
	public final structuralDepth:Int;
	public final traceAnchor:Bool;

	public function new(id:String, nodeKind:String, generatedStartByte:Int, generatedEndByte:Int, source:PhpSourceRange, semanticNodeId:String,
			structuralDepth:Int, traceAnchor:Bool) {
		this.id = PhpStableId.validate(id, "mapping ID");
		this.nodeKind = validateNodeKind(nodeKind);
		if (generatedStartByte < 0
			|| generatedEndByte <= generatedStartByte
			|| source == null
			|| !source.isExact
			|| structuralDepth < 0) {
			throw "Rendered PHP mapping is invalid";
		}
		this.generatedStartByte = generatedStartByte;
		this.generatedEndByte = generatedEndByte;
		this.source = source;
		this.semanticNodeId = PhpStableId.validate(semanticNodeId, "semantic node ID");
		this.structuralDepth = structuralDepth;
		this.traceAnchor = traceAnchor;
	}

	static function validateNodeKind(value:String):String {
		return switch (value) {
			case "file", "declaration", "member", "statement", "expression", "markup", "adapter", "compiler-generated": value;
			case _: throw "Unsupported PHP mapping node kind: " + value;
		}
	}
}
