#!/usr/bin/env python3
"""Verify the semantic matrix's per-module PHP graph against authored source facts."""

from __future__ import annotations

import hashlib
import json
import re
import sys
from pathlib import Path


def require(condition: bool, message: str) -> None:
    if not condition:
        raise SystemExit(message)


def digest(contents: bytes) -> str:
    return hashlib.sha256(contents).hexdigest()


def verify_ownership(output_root: Path, expected_paths: set[str]) -> None:
    ownership = output_root / ".reflaxe.php-owned-files.v1"
    lines = ownership.read_text(encoding="utf-8").splitlines()
    require(lines and lines[0] == "reflaxe.php-owned-files.v1", "ownership header drifted")
    records: dict[str, tuple[str, int]] = {}
    for line in lines[1:]:
        fields = line.split("\t")
        require(len(fields) == 3 and re.fullmatch(r"[0-9a-f]{64}", fields[0]) is not None, "ownership record drifted")
        records[fields[2]] = (fields[0], int(fields[1]))
    require(list(records) == sorted(records), "ownership records are not canonical")
    require(set(records) == expected_paths - {ownership.name}, "ownership path inventory drifted")
    for path, (sha256, byte_length) in records.items():
        contents = (output_root / path).read_bytes()
        require(digest(contents) == sha256, f"ownership digest drifted for {path}")
        require(len(contents) == byte_length, f"ownership byte length drifted for {path}")


def verify_map(
    output_root: Path,
    generated_path: str,
    source_path: str,
    source: bytes,
    expected: dict[str, tuple[str, int, bytes]],
    expected_anchors: set[str],
) -> None:
    generated = (output_root / generated_path).read_bytes()
    document = json.loads((output_root / (generated_path + ".haxe-map.json")).read_text(encoding="utf-8"))
    require(document["format"] == "reflaxe.php-range-map.v1", f"range-map format drifted for {generated_path}")
    require(document["generated"]["path"] == generated_path, f"generated path drifted for {generated_path}")
    require(document["generated"]["sha256"] == digest(generated), f"generated digest drifted for {generated_path}")
    require(document["generated"]["byteLength"] == len(generated), f"generated byte length drifted for {generated_path}")
    sources = document["sources"]
    require(len(sources) == 1, f"{generated_path} must bind one source")
    source_record = sources[0]
    require(source_record["path"] == source_path, f"source path drifted for {generated_path}")
    require(source_record["id"] == "source:" + source_path, f"source identity drifted for {generated_path}")
    require(source_record["sha256"] == digest(source), f"source digest drifted for {generated_path}")
    require(source_record["byteLength"] == len(source), f"source byte length drifted for {generated_path}")
    mappings = document["mappings"]
    require({mapping["id"] for mapping in mappings} == set(expected), f"mapping identities drifted for {generated_path}")
    for mapping in mappings:
        mapping_id = mapping["id"]
        node_kind, structural_depth, fragment = expected[mapping_id]
        require(mapping["nodeKind"] == node_kind, f"node kind drifted for {mapping_id}")
        require(mapping["structuralDepth"] == structural_depth, f"mapping depth drifted for {mapping_id}")
        origin = mapping["origin"]
        require(origin["sourceId"] == source_record["id"], f"source identity drifted for {mapping_id}")
        span = origin["sourceSpan"]
        require(fragment in source[span["startByte"] : span["endByte"]], f"source span lost its owner for {mapping_id}")
        generated_span = mapping["generatedSpan"]
        require(
            0 <= generated_span["startByte"] < generated_span["endByte"] <= len(generated),
            f"generated span drifted for {mapping_id}",
        )
    require({anchor["mappingId"] for anchor in document["traceAnchors"]} == expected_anchors, f"trace anchors drifted for {generated_path}")


def main() -> None:
    require(len(sys.argv) == 3, "usage: verify-semantic-matrix.py SOURCE_ROOT OUTPUT_ROOT")
    source_root = Path(sys.argv[1])
    output_root = Path(sys.argv[2])
    sources = {
        path.relative_to(source_root).as_posix(): path.read_bytes()
        for path in sorted(source_root.rglob("*.hx"))
    }
    calculator_path = "modules/9_semantics/10_Calculator/10_Calculator.php"
    main_path = "modules/9_semantics/4_Main/4_Main.php"
    expected_paths = {
        ".reflaxe.php-owned-files.v1",
        "bootstrap.php",
        "bootstrap.php.haxe-map.json",
        calculator_path,
        calculator_path + ".haxe-map.json",
        main_path,
        main_path + ".haxe-map.json",
        "reflaxe.php-artifacts.json",
    }
    actual_paths = {
        path.relative_to(output_root).as_posix()
        for path in output_root.rglob("*")
        if path.is_file()
    }
    require(actual_paths == expected_paths, "semantic artifact inventory drifted")

    artifact_manifest = json.loads((output_root / "reflaxe.php-artifacts.json").read_text(encoding="utf-8"))
    require(artifact_manifest["schemaVersion"] == 1, "artifact manifest schema drifted")
    require(artifact_manifest["format"] == "reflaxe.php-artifact-graph.v1", "artifact manifest format drifted")
    require(artifact_manifest["profile"] == {
        "id": "php74-modern-v1",
        "minimumPhpVersionId": 70400,
        "nativeIntTypes": True,
        "strictTypes": True,
    }, "semantic PHP profile drifted")
    require(artifact_manifest["entrypoint"] == {
        "identity": "semantics.Main@Main",
        "method": "main",
        "path": "bootstrap.php",
    }, "semantic entrypoint drifted")
    require(artifact_manifest["loadOrder"] == [calculator_path, main_path], "source-derived load order drifted")
    artifacts = {artifact["path"]: artifact for artifact in artifact_manifest["artifacts"]}
    require(set(artifacts) == {"bootstrap.php", calculator_path, main_path}, "artifact records drifted")
    require(artifacts[calculator_path]["dependencies"] == [], "calculator dependencies drifted")
    require(artifacts[main_path]["dependencies"] == ["semantics.Calculator@Calculator"], "main dependency edge drifted")
    require(
        artifacts["bootstrap.php"]["dependencies"] == ["semantics.Calculator@Calculator", "semantics.Main@Main"],
        "bootstrap dependencies drifted",
    )
    for path, artifact in artifacts.items():
        require(artifact["sha256"] == digest((output_root / path).read_bytes()), f"artifact digest drifted for {path}")
        require(artifact["mapSha256"] == digest((output_root / artifact["mapPath"]).read_bytes()), f"artifact map digest drifted for {path}")

    calculator_expected = {
        "class:semantics.Calculator:Calculator": ("declaration", 0, b"class Calculator"),
        "method:semantics.Calculator:add": ("member", 1, b"public static function add"),
        "stmt:return-int:96:115": ("statement", 2, b"return left + right"),
    }
    main_expected = {
        "class:semantics.Main:Main": ("declaration", 0, b"class Main"),
        "method:semantics.Main:main": ("member", 1, b"public static function main"),
        "stmt:local-int:73:110": ("statement", 2, b"final answer = Calculator.add(40, 2)"),
        "stmt:if-int-equality:113:237": ("statement", 2, b"if (answer == 42)"),
        "stmt:sys-println:136:176": ("statement", 3, b'Sys.println("numeric-control-flow:pass")'),
        "stmt:sys-println:192:232": ("statement", 3, b'Sys.println("numeric-control-flow:fail")'),
        "stmt:local-int:241:255": ("statement", 2, b"var total = 0"),
        "stmt:local-int:258:274": ("statement", 2, b"var current = 1"),
        "stmt:while-int:277:357": ("statement", 2, b"while (current <= 4)"),
        "stmt:assign-int:303:326": ("statement", 3, b"total = total + current"),
        "stmt:assign-int:331:352": ("statement", 3, b"current = current + 1"),
        "stmt:if-int-equality:360:467": ("statement", 2, b"if (total == 10)"),
        "stmt:sys-println:382:414": ("statement", 3, b'Sys.println("mutable-loop:pass")'),
        "stmt:sys-println:430:462": ("statement", 3, b'Sys.println("mutable-loop:fail")'),
        "stmt:local-int-array:471:496": ("statement", 2, b"final values = [3, 1, 4]"),
        "stmt:local-int:499:538": ("statement", 2, b"final selected = values[1] + values[2]"),
        "stmt:if-int-equality:541:654": ("statement", 2, b"if (selected == 5)"),
        "stmt:sys-println:565:599": ("statement", 3, b'Sys.println("int-array-read:pass")'),
        "stmt:sys-println:615:649": ("statement", 3, b'Sys.println("int-array-read:fail")'),
    }
    verify_map(output_root, calculator_path, "semantics/Calculator.hx", sources["semantics/Calculator.hx"], calculator_expected,
        {"stmt:return-int:96:115"})
    verify_map(
        output_root,
        main_path,
        "semantics/Main.hx",
        sources["semantics/Main.hx"],
        main_expected,
        {mapping_id for mapping_id in main_expected if mapping_id.startswith("stmt:")},
    )
    verify_map(
        output_root,
        "bootstrap.php",
        "semantics/Main.hx",
        sources["semantics/Main.hx"],
        {"entrypoint:semantics.Main:Main": ("statement", 0, b"class Main")},
        set(),
    )
    verify_ownership(output_root, expected_paths)
    output_text = "\n".join(path.read_text(encoding="utf-8") for path in output_root.rglob("*") if path.is_file())
    require(str(output_root.resolve()) not in output_text, "machine path leaked into semantic artifacts")
    print("reflaxe.php per-module numeric/control-flow/function-call/while/array maps passed")


if __name__ == "__main__":
    main()
