#!/usr/bin/env python3
"""Verify the semantic matrix's per-module PHP graph against authored source facts."""

from __future__ import annotations

import hashlib
import json
import re
import sys
from pathlib import Path


def require(condition: bool, message: str) -> None:
    if not condition:
        raise SystemExit(message)


def digest(contents: bytes) -> str:
    return hashlib.sha256(contents).hexdigest()


def verify_ownership(output_root: Path, expected_paths: set[str]) -> None:
    ownership = output_root / ".reflaxe.php-owned-files.v1"
    lines = ownership.read_text(encoding="utf-8").splitlines()
    require(lines and lines[0] == "reflaxe.php-owned-files.v1", "ownership header drifted")
    records: dict[str, tuple[str, int]] = {}
    for line in lines[1:]:
        fields = line.split("\t")
        require(len(fields) == 3 and re.fullmatch(r"[0-9a-f]{64}", fields[0]) is not None, "ownership record drifted")
        records[fields[2]] = (fields[0], int(fields[1]))
    require(list(records) == sorted(records), "ownership records are not canonical")
    require(set(records) == expected_paths - {ownership.name}, "ownership path inventory drifted")
    for path, (sha256, byte_length) in records.items():
        contents = (output_root / path).read_bytes()
        require(digest(contents) == sha256, f"ownership digest drifted for {path}")
        require(len(contents) == byte_length, f"ownership byte length drifted for {path}")


def verify_map(
    output_root: Path,
    generated_path: str,
    source_path: str,
    source: bytes,
    expected: dict[str, tuple[str, int, bytes]],
    expected_anchors: set[str],
) -> None:
    generated = (output_root / generated_path).read_bytes()
    source_text = source.decode("utf-8")
    document = json.loads((output_root / (generated_path + ".haxe-map.json")).read_text(encoding="utf-8"))
    require(document["format"] == "reflaxe.php-range-map.v1", f"range-map format drifted for {generated_path}")
    require(document["generated"]["path"] == generated_path, f"generated path drifted for {generated_path}")
    require(document["generated"]["sha256"] == digest(generated), f"generated digest drifted for {generated_path}")
    require(document["generated"]["byteLength"] == len(generated), f"generated byte length drifted for {generated_path}")
    sources = document["sources"]
    require(len(sources) == 1, f"{generated_path} must bind one source")
    source_record = sources[0]
    require(source_record["path"] == source_path, f"source path drifted for {generated_path}")
    require(source_record["id"] == "source:" + source_path, f"source identity drifted for {generated_path}")
    require(source_record["sha256"] == digest(source), f"source digest drifted for {generated_path}")
    require(source_record["byteLength"] == len(source), f"source byte length drifted for {generated_path}")
    mappings = document["mappings"]
    require({mapping["id"] for mapping in mappings} == set(expected), f"mapping identities drifted for {generated_path}")
    for mapping in mappings:
        mapping_id = mapping["id"]
        node_kind, structural_depth, fragment = expected[mapping_id]
        require(mapping["nodeKind"] == node_kind, f"node kind drifted for {mapping_id}")
        require(mapping["structuralDepth"] == structural_depth, f"mapping depth drifted for {mapping_id}")
        origin = mapping["origin"]
        require(origin["sourceId"] == source_record["id"], f"source identity drifted for {mapping_id}")
        span = origin["sourceSpan"]
        require(fragment in source[span["startByte"] : span["endByte"]], f"source span lost its owner for {mapping_id}")
        haxe_offsets = re.search(r":([0-9]+):([0-9]+)$", mapping_id)
        if haxe_offsets is not None:
            start_character = int(haxe_offsets.group(1))
            end_character = int(haxe_offsets.group(2))
            require(
                span["startByte"] == len(source_text[:start_character].encode("utf-8")),
                f"Haxe character-to-byte start conversion drifted for {mapping_id}",
            )
            require(
                span["endByte"] == len(source_text[:end_character].encode("utf-8")),
                f"Haxe character-to-byte end conversion drifted for {mapping_id}",
            )
        generated_span = mapping["generatedSpan"]
        require(
            0 <= generated_span["startByte"] < generated_span["endByte"] <= len(generated),
            f"generated span drifted for {mapping_id}",
        )
    require({anchor["mappingId"] for anchor in document["traceAnchors"]} == expected_anchors, f"trace anchors drifted for {generated_path}")


def main() -> None:
    require(len(sys.argv) == 3, "usage: verify-semantic-matrix.py SOURCE_ROOT OUTPUT_ROOT")
    source_root = Path(sys.argv[1])
    output_root = Path(sys.argv[2])
    sources = {
        path.relative_to(source_root).as_posix(): path.read_bytes()
        for path in sorted(source_root.rglob("*.hx"))
    }
    calculator_path = "modules/9_semantics/10_Calculator/10_Calculator.php"
    greeter_path = "modules/9_semantics/7_Greeter/7_Greeter.php"
    main_path = "modules/9_semantics/4_Main/4_Main.php"
    runtime_path = "runtime/ReflaxePhpStringRuntime.php"
    expected_paths = {
        ".reflaxe.php-owned-files.v1",
        "bootstrap.php",
        "bootstrap.php.haxe-map.json",
        calculator_path,
        calculator_path + ".haxe-map.json",
        greeter_path,
        greeter_path + ".haxe-map.json",
        main_path,
        main_path + ".haxe-map.json",
        runtime_path,
        runtime_path + ".haxe-map.json",
        "reflaxe.php-artifacts.json",
    }
    actual_paths = {
        path.relative_to(output_root).as_posix()
        for path in output_root.rglob("*")
        if path.is_file()
    }
    require(actual_paths == expected_paths, "semantic artifact inventory drifted")

    artifact_manifest = json.loads((output_root / "reflaxe.php-artifacts.json").read_text(encoding="utf-8"))
    require(artifact_manifest["schemaVersion"] == 1, "artifact manifest schema drifted")
    require(artifact_manifest["format"] == "reflaxe.php-artifact-graph.v1", "artifact manifest format drifted")
    require(artifact_manifest["profile"] == {
        "id": "php74-modern-v1",
        "minimumPhpVersionId": 70400,
        "nativeIntTypes": True,
        "strictTypes": True,
    }, "semantic PHP profile drifted")
    require(artifact_manifest["entrypoint"] == {
        "identity": "semantics.Main@Main",
        "method": "main",
        "path": "bootstrap.php",
    }, "semantic entrypoint drifted")
    require(
        artifact_manifest["loadOrder"] == [calculator_path, greeter_path, runtime_path, main_path],
        "source-derived load order drifted",
    )
    artifacts = {artifact["path"]: artifact for artifact in artifact_manifest["artifacts"]}
    require(
        set(artifacts) == {"bootstrap.php", calculator_path, greeter_path, main_path, runtime_path},
        "artifact records drifted",
    )
    require(artifacts[runtime_path]["kind"] == "runtime", "string runtime artifact kind drifted")
    require(artifacts[runtime_path]["identity"] == "runtime:string", "string runtime identity drifted")
    require(artifacts[runtime_path]["dependencies"] == [], "string runtime dependencies drifted")
    require(artifacts[calculator_path]["dependencies"] == [], "calculator dependencies drifted")
    require(artifacts[greeter_path]["dependencies"] == [], "greeter dependencies drifted")
    require(
        artifacts[main_path]["dependencies"]
        == ["runtime:string", "semantics.Calculator@Calculator", "semantics.Greeter@Greeter"],
        "main dependency edge drifted",
    )
    require(
        artifacts["bootstrap.php"]["dependencies"]
        == ["runtime:string", "semantics.Calculator@Calculator", "semantics.Greeter@Greeter", "semantics.Main@Main"],
        "bootstrap dependencies drifted",
    )
    for path, artifact in artifacts.items():
        require(artifact["sha256"] == digest((output_root / path).read_bytes()), f"artifact digest drifted for {path}")
        require(artifact["mapSha256"] == digest((output_root / artifact["mapPath"]).read_bytes()), f"artifact map digest drifted for {path}")

    calculator_expected = {
        "class:semantics.Calculator:Calculator": ("declaration", 0, b"class Calculator"),
        "method:semantics.Calculator:add": ("member", 1, b"public static function add"),
        "stmt:return-int:96:115": ("statement", 2, b"return left + right"),
        "method:semantics.Calculator:decorate": ("member", 1, b"public static function decorate"),
        "stmt:return-string:194:215": ("statement", 2, b"return prefix + value"),
        "method:semantics.Calculator:isMissing": ("member", 1, b"public static function isMissing"),
        "stmt:return-bool:284:304": ("statement", 2, b"return value == null"),
        "method:semantics.Calculator:isPresent": ("member", 1, b"public static function isPresent"),
        "stmt:return-bool:373:393": ("statement", 2, b"return value != null"),
        "method:semantics.Calculator:roundTrip": ("member", 1, b"public static function roundTrip"),
        "stmt:return-nullable-string:470:482": ("statement", 2, b"return value"),
        "method:semantics.Calculator:negate": ("member", 1, b"public static function negate"),
        "stmt:return-bool:540:553": ("statement", 2, b"return !value"),
        "method:semantics.Calculator:probe": ("member", 1, b"public static function probe"),
        "stmt:sys-println:610:635": ("statement", 2, b'Sys.println("bool-probe")'),
        "stmt:return-bool:639:651": ("statement", 2, b"return value"),
    }
    greeter_expected = {
        "class:semantics.Greeter:Greeter": ("declaration", 0, b"class Greeter"),
        "method:semantics.Greeter:new": ("member", 1, b"public function new"),
        "stmt:assign-instance-string:99:119": ("statement", 2, b"this.prefix = prefix"),
        "method:semantics.Greeter:render": ("member", 1, b"public function render"),
        "stmt:return-string:174:200": ("statement", 2, b"return this.prefix + value"),
    }
    main_expected = {
        "class:semantics.Main:Main": ("declaration", 0, b"class Main"),
        "method:semantics.Main:main": ("member", 1, b"public static function main"),
        "stmt:local-int:73:110": ("statement", 2, b"final answer = Calculator.add(40, 2)"),
        "stmt:if-int-equality:113:237": ("statement", 2, b"if (answer == 42)"),
        "stmt:sys-println:136:176": ("statement", 3, b'Sys.println("numeric-control-flow:pass")'),
        "stmt:sys-println:192:232": ("statement", 3, b'Sys.println("numeric-control-flow:fail")'),
        "stmt:local-int:241:255": ("statement", 2, b"var total = 0"),
        "stmt:local-int:258:274": ("statement", 2, b"var current = 1"),
        "stmt:while-int:277:357": ("statement", 2, b"while (current <= 4)"),
        "stmt:assign-int:303:326": ("statement", 3, b"total = total + current"),
        "stmt:assign-int:331:352": ("statement", 3, b"current = current + 1"),
        "stmt:if-int-equality:360:467": ("statement", 2, b"if (total == 10)"),
        "stmt:sys-println:382:414": ("statement", 3, b'Sys.println("mutable-loop:pass")'),
        "stmt:sys-println:430:462": ("statement", 3, b'Sys.println("mutable-loop:fail")'),
        "stmt:local-int-array:471:496": ("statement", 2, b"final values = [3, 1, 4]"),
        "stmt:local-int:499:538": ("statement", 2, b"final selected = values[1] + values[2]"),
        "stmt:if-int-equality:541:654": ("statement", 2, b"if (selected == 5)"),
        "stmt:sys-println:565:599": ("statement", 3, b'Sys.println("int-array-read:pass")'),
        "stmt:sys-println:615:649": ("statement", 3, b'Sys.println("int-array-read:fail")'),
        "stmt:local-string:658:712": ("statement", 2, 'final label = Calculator.decorate("Haxe ", "→ PHP 🚀")'.encode("utf-8")),
        "stmt:sys-println:715:733": ("statement", 2, b"Sys.println(label)"),
        "stmt:if-string-equality:737:860": ("statement", 2, 'if (label == "Haxe → PHP 🚀")'.encode("utf-8")),
        "stmt:sys-println:771:805": ("statement", 3, b'Sys.println("unicode-string:pass")'),
        "stmt:sys-println:821:855": ("statement", 3, b'Sys.println("unicode-string:fail")'),
        "stmt:local-bool:864:905": ("statement", 2, b"final enabled = Calculator.negate(false)"),
        "stmt:if-bool:908:1011": ("statement", 2, b"if (enabled)"),
        "stmt:sys-println:926:958": ("statement", 3, b'Sys.println("bool-control:pass")'),
        "stmt:sys-println:974:1006": ("statement", 3, b'Sys.println("bool-control:fail")'),
        "stmt:local-bool:1015:1066": ("statement", 2, b"final andSkipped = false && Calculator.probe(true)"),
        "stmt:local-bool:1069:1119": ("statement", 2, b"final orSkipped = true || Calculator.probe(false)"),
        "stmt:local-bool:1122:1175": ("statement", 2, b"final andEvaluated = true && Calculator.probe(false)"),
        "stmt:local-bool:1178:1237": ("statement", 2, b"final grouped = (true || Calculator.probe(false)) && false"),
        "stmt:if-bool:1240:1401": ("statement", 2, b"if (!andSkipped && orSkipped && !andEvaluated && !grouped)"),
        "stmt:sys-println:1304:1342": ("statement", 3, b'Sys.println("bool-short-circuit:pass")'),
        "stmt:sys-println:1358:1396": ("statement", 3, b'Sys.println("bool-short-circuit:fail")'),
        "stmt:local-object:1405:1453": ("statement", 2, b'final greeter = new Greeter("instance-layout:")'),
        "stmt:sys-println:1456:1491": ("statement", 2, b'Sys.println(greeter.render("pass"))'),
        "stmt:local-string:1496:1530": ("statement", 2, b'final prefix = "closure-capture:"'),
        "stmt:local-string-closure:1533:1610": ("statement", 2, b"final render = function(value:String):String"),
        "stmt:return-string:1583:1604": ("statement", 3, b"return prefix + value"),
        "stmt:sys-println:1613:1640": ("statement", 2, b'Sys.println(render("pass"))'),
        "stmt:try-haxe-exception:1645:1915": ("statement", 2, b"try {"),
        "stmt:throw-haxe-exception:1654:1700": ("statement", 3, b'throw new haxe.Exception("expected-exception")'),
        "stmt:local-string:1740:1770": ("statement", 3, b"final message = error.message"),
        "stmt:if-string-equality:1774:1911": ("statement", 3, b'if (message == "expected-exception")'),
        "stmt:sys-println:1817:1852": ("statement", 4, b'Sys.println("exception-catch:pass")'),
        "stmt:sys-println:1870:1905": ("statement", 4, b'Sys.println("exception-catch:fail")'),
        "stmt:local-nullable-string:1919:1953": ("statement", 2, b"final missing:Null<String> = null"),
        "stmt:local-nullable-string:1956:1995": ("statement", 2, b'final present:Null<String> = "present"'),
        "stmt:if-bool:1998:2226": ("statement", 2, b"if (Calculator.isMissing(missing)"),
        "stmt:sys-println:2135:2170": ("statement", 3, b'Sys.println("nullable-string:pass")'),
        "stmt:sys-println:2186:2221": ("statement", 3, b'Sys.println("nullable-string:fail")'),
        "stmt:local-nullable-string:2230:2297": ("statement", 2, b"final returnedMissing:Null<String> = Calculator.roundTrip(missing)"),
        "stmt:local-nullable-string:2300:2367": ("statement", 2, b"final returnedPresent:Null<String> = Calculator.roundTrip(present)"),
        "stmt:if-bool:2370:2564": ("statement", 2, b"if (Calculator.isMissing(returnedMissing)"),
        "stmt:sys-println:2459:2501": ("statement", 3, b'Sys.println("nullable-string-return:pass")'),
        "stmt:sys-println:2517:2559": ("statement", 3, b'Sys.println("nullable-string-return:fail")'),
        "stmt:local-int:2568:2602": ("statement", 2, 'final unicodeLength = "A🚀".length'.encode("utf-8")),
        "stmt:if-int-equality:2605:2737": ("statement", 2, b"if (unicodeLength == 2)"),
        "stmt:sys-println:2634:2675": ("statement", 3, b'Sys.println("unicode-string-length:pass")'),
        "stmt:sys-println:2691:2732": ("statement", 3, b'Sys.println("unicode-string-length:fail")'),
        "stmt:local-int:2741:2774": ("statement", 2, b"final valueCount = values.length"),
        "stmt:if-int-equality:2777:2896": ("statement", 2, b"if (valueCount == 3)"),
		"stmt:sys-println:2803:2839": ("statement", 3, b'Sys.println("int-array-length:pass")'),
		"stmt:sys-println:2855:2891": ("statement", 3, b'Sys.println("int-array-length:fail")'),
        "stmt:int-array-push:2900:2914": ("statement", 2, b"values.push(5)"),
        "stmt:local-int:2918:2952": ("statement", 2, b"final pushedCount = values.length"),
        "stmt:local-int:2955:2985": ("statement", 2, b"final pushedValue = values[3]"),
        "stmt:local-int:2988:3036": ("statement", 2, b"final pushedSummary = pushedCount + pushedValue"),
        "stmt:if-int-equality:3039:3157": ("statement", 2, b"if (pushedSummary == 9)"),
        "stmt:sys-println:3068:3102": ("statement", 3, b'Sys.println("int-array-push:pass")'),
        "stmt:sys-println:3118:3152": ("statement", 3, b'Sys.println("int-array-push:fail")'),
	}
    verify_map(output_root, calculator_path, "semantics/Calculator.hx", sources["semantics/Calculator.hx"], calculator_expected,
        {
            "stmt:return-int:96:115",
            "stmt:return-string:194:215",
            "stmt:return-bool:284:304",
            "stmt:return-bool:373:393",
            "stmt:return-nullable-string:470:482",
            "stmt:return-bool:540:553",
            "stmt:sys-println:610:635",
            "stmt:return-bool:639:651",
        })
    verify_map(
        output_root,
        greeter_path,
        "semantics/Greeter.hx",
        sources["semantics/Greeter.hx"],
        greeter_expected,
        {"stmt:assign-instance-string:99:119", "stmt:return-string:174:200"},
    )
    verify_map(
        output_root,
        main_path,
        "semantics/Main.hx",
        sources["semantics/Main.hx"],
        main_expected,
        {mapping_id for mapping_id in main_expected if mapping_id.startswith("stmt:")},
    )
    verify_map(
        output_root,
        runtime_path,
        "semantics/Main.hx",
        sources["semantics/Main.hx"],
        {
            "runtime:string": ("declaration", 0, '"A🚀".length'.encode("utf-8")),
            "runtime:string-length": ("member", 1, '"A🚀".length'.encode("utf-8")),
        },
        set(),
    )
    verify_map(
        output_root,
        "bootstrap.php",
        "semantics/Main.hx",
        sources["semantics/Main.hx"],
        {"entrypoint:semantics.Main:Main": ("statement", 0, b"class Main")},
        set(),
    )
    verify_ownership(output_root, expected_paths)
    output_text = "\n".join(path.read_text(encoding="utf-8") for path in output_root.rglob("*") if path.is_file())
    require(str(output_root.resolve()) not in output_text, "machine path leaked into semantic artifacts")
    print("reflaxe.php per-module numeric/control-flow/function-call/while/array/string/bool/instance-layout/closure/exception/null/runtime maps passed")


if __name__ == "__main__":
    main()
