#!/usr/bin/env python3
"""Independently verify the ordinary-Haxe per-module artifact graph and maps."""

from __future__ import annotations

import hashlib
import json
import re
import sys
from pathlib import Path


def require(condition: bool, message: str) -> None:
    if not condition:
        raise SystemExit(message)


def sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def verify_ownership(output_root: Path, expected_paths: set[str]) -> None:
    manifest_path = output_root / ".reflaxe.php-owned-files.v1"
    lines = manifest_path.read_text(encoding="utf-8").splitlines()
    require(lines and lines[0] == "reflaxe.php-owned-files.v1", "ownership header drifted")
    records: dict[str, tuple[str, int]] = {}
    for line in lines[1:]:
        fields = line.split("\t")
        require(len(fields) == 3, "ownership record shape drifted")
        digest, byte_length, path = fields
        require(re.fullmatch(r"[0-9a-f]{64}", digest) is not None, "ownership digest drifted")
        require(path not in records, "duplicate ownership path")
        records[path] = (digest, int(byte_length))
    require(list(records) == sorted(records), "ownership records are not canonical")
    require(set(records) == expected_paths - {manifest_path.name}, "ownership inventory drifted")
    for path, (digest, byte_length) in records.items():
        contents = (output_root / path).read_bytes()
        require(sha256(contents) == digest, f"ownership digest drifted for {path}")
        require(len(contents) == byte_length, f"ownership byte length drifted for {path}")


def verify_map(
    output_root: Path,
    map_path: str,
    generated_path: str,
    source_path: Path,
    expected_mappings: dict[str, tuple[str, int, bytes]],
    expected_anchor_ids: set[str],
) -> None:
    generated = (output_root / generated_path).read_bytes()
    source = source_path.read_bytes()
    document = json.loads((output_root / map_path).read_text(encoding="utf-8"))
    require(document["schemaVersion"] == 1, "unexpected range-map schema")
    require(document["format"] == "reflaxe.php-range-map.v1", "unexpected range-map format")
    require(document["generator"]["id"] == "reflaxe.php.compiler", "unexpected generator")
    require(document["generator"]["version"] == "0.0.0", "unexpected generator version")
    require(document["generated"]["path"] == generated_path, f"generated path drifted for {map_path}")
    require(document["generated"]["byteLength"] == len(generated), f"generated byte length drifted for {map_path}")
    require(document["generated"]["sha256"] == sha256(generated), f"generated digest drifted for {map_path}")
    sources = document["sources"]
    require(len(sources) == 1, f"{map_path} must bind exactly one source")
    source_record = sources[0]
    require(source_record["id"] == "source:tracer/Main.hx", "unexpected tracer source identity")
    require(source_record["path"] == "tracer/Main.hx", "tracer source path drifted")
    require(source_record["sha256"] == sha256(source), "tracer source digest drifted")
    require(source_record["byteLength"] == len(source), "tracer source byte length drifted")
    mappings = document["mappings"]
    require({mapping["id"] for mapping in mappings} == set(expected_mappings), f"mapping identities drifted for {map_path}")
    for mapping in mappings:
        mapping_id = mapping["id"]
        node_kind, depth, fragment = expected_mappings[mapping_id]
        require(mapping["nodeKind"] == node_kind, f"node kind drifted for {mapping_id}")
        require(mapping["structuralDepth"] == depth, f"depth drifted for {mapping_id}")
        origin = mapping["origin"]
        require(origin["kind"] == "haxe-source", f"origin kind drifted for {mapping_id}")
        require(origin["sourceId"] == source_record["id"], f"source identity drifted for {mapping_id}")
        span = origin["sourceSpan"]
        require(fragment in source[span["startByte"] : span["endByte"]], f"source span lost semantic owner for {mapping_id}")
        generated_span = mapping["generatedSpan"]
        require(
            0 <= generated_span["startByte"] < generated_span["endByte"] <= len(generated),
            f"generated span drifted for {mapping_id}",
        )
    require({anchor["mappingId"] for anchor in document["traceAnchors"]} == expected_anchor_ids, f"trace anchors drifted for {map_path}")


def main() -> None:
    require(len(sys.argv) == 3, "usage: verify-compiler-tracer.py SOURCE OUTPUT_ROOT")
    source_path = Path(sys.argv[1])
    output_root = Path(sys.argv[2])
    module_path = "modules/6_tracer/4_Main/4_Main.php"
    expected_paths = {
        ".reflaxe.php-owned-files.v1",
        "bootstrap.php",
        "bootstrap.php.haxe-map.json",
        module_path,
        module_path + ".haxe-map.json",
        "reflaxe.php-artifacts.json",
    }
    actual_paths = {
        path.relative_to(output_root).as_posix()
        for path in output_root.rglob("*")
        if path.is_file()
    }
    require(actual_paths == expected_paths, "tracer artifact inventory drifted")
    artifact_manifest = json.loads((output_root / "reflaxe.php-artifacts.json").read_text(encoding="utf-8"))
    require(artifact_manifest["format"] == "reflaxe.php-artifact-graph.v1", "artifact graph format drifted")
    require(artifact_manifest["profile"] == {
        "id": "php74-modern-v1",
        "minimumPhpVersionId": 70400,
        "nativeIntTypes": True,
        "strictTypes": True,
    }, "PHP profile drifted")
    require(artifact_manifest["entrypoint"] == {
        "identity": "tracer.Main@Main",
        "method": "main",
        "path": "bootstrap.php",
    }, "tracer entrypoint drifted")
    require(artifact_manifest["loadOrder"] == [module_path], "tracer load order drifted")
    artifacts = {artifact["path"]: artifact for artifact in artifact_manifest["artifacts"]}
    require(set(artifacts) == {"bootstrap.php", module_path}, "tracer artifact records drifted")
    require(artifacts[module_path]["dependencies"] == [], "tracer module gained a dependency")
    require(artifacts["bootstrap.php"]["dependencies"] == ["tracer.Main@Main"], "bootstrap dependencies drifted")
    for path, artifact in artifacts.items():
        require(artifact["sha256"] == sha256((output_root / path).read_bytes()), f"artifact digest drifted for {path}")
        require(artifact["mapSha256"] == sha256((output_root / artifact["mapPath"]).read_bytes()), f"map digest drifted for {path}")

    verify_map(
        output_root,
        module_path + ".haxe-map.json",
        module_path,
        source_path,
        {
            "class:tracer.Main:Main": ("declaration", 0, b"class Main"),
            "method:tracer.Main:main": ("member", 1, b"public static function main"),
            "stmt:sys-println:70:113": ("statement", 2, b'Sys.println("reflaxe.php typed PHP tracer")'),
        },
        {"stmt:sys-println:70:113"},
    )
    verify_map(
        output_root,
        "bootstrap.php.haxe-map.json",
        "bootstrap.php",
        source_path,
        {"entrypoint:tracer.Main:Main": ("statement", 0, b"class Main")},
        set(),
    )
    verify_ownership(output_root, expected_paths)
    output_text = "\n".join(path.read_text(encoding="utf-8") for path in output_root.rglob("*") if path.is_file())
    require(str(output_root.resolve()) not in output_text, "machine path leaked into tracer artifacts")
    print("reflaxe.php ordinary-Haxe per-module artifact graph passed")


if __name__ == "__main__":
    main()
