#!/usr/bin/env python3
"""Independently verify the ordinary-Haxe tracer range map and its source slices."""

from __future__ import annotations

import hashlib
import json
import sys
from pathlib import Path


def require(condition: bool, message: str) -> None:
    if not condition:
        raise SystemExit(message)


def sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def main() -> None:
    require(len(sys.argv) == 4, "usage: verify-compiler-tracer.py SOURCE PHP MAP")
    source_path = Path(sys.argv[1])
    php_path = Path(sys.argv[2])
    map_path = Path(sys.argv[3])
    source = source_path.read_bytes()
    generated = php_path.read_bytes()
    document = json.loads(map_path.read_text(encoding="utf-8"))

    require(document["schemaVersion"] == 1, "unexpected range-map schema")
    require(document["format"] == "reflaxe.php-range-map.v1", "unexpected range-map format")
    require(document["generator"]["id"] == "reflaxe.php.compiler", "unexpected generator")
    require(document["generator"]["version"] == "0.0.0", "unexpected generator version")
    require(document["generated"]["path"] == "main.php", "unexpected generated path")
    require(document["generated"]["byteLength"] == len(generated), "generated byte length drifted")
    require(document["generated"]["sha256"] == sha256(generated), "generated digest drifted")

    sources = document["sources"]
    require(len(sources) == 1, "tracer must map exactly one application source")
    source_record = sources[0]
    require(source_record["id"] == "source:tracer/Main.hx", "unexpected source identity")
    require(source_record["path"] == "tracer/Main.hx", "source path leaked or drifted")
    require(source_record["rootId"] == "reflaxe.php.application", "unexpected source root")
    require(source_record["byteLength"] == len(source), "source byte length drifted")
    require(source_record["sha256"] == sha256(source), "source digest drifted")

    expected = {
        "class:tracer.Main:Main": ("declaration", 0, b"class Main"),
        "method:tracer.Main:main": ("member", 1, b"public static function main"),
        "stmt:sys-println:70:113": ("statement", 2, b'Sys.println("reflaxe.php typed PHP tracer")'),
        "entrypoint:tracer.Main:Main": ("statement", 0, b"class Main"),
    }
    mappings = document["mappings"]
    require(len(mappings) == len(expected), "unexpected tracer mapping count")
    observed_ids = {mapping["id"] for mapping in mappings}
    require(observed_ids == set(expected), "tracer mapping identities drifted")
    for mapping in mappings:
        mapping_id = mapping["id"]
        node_kind, depth, source_fragment = expected[mapping_id]
        require(mapping["nodeKind"] == node_kind, f"node kind drifted for {mapping_id}")
        require(mapping["structuralDepth"] == depth, f"depth drifted for {mapping_id}")
        origin = mapping["origin"]
        require(origin["kind"] == "haxe-source", f"origin kind drifted for {mapping_id}")
        require(origin["sourceId"] == source_record["id"], f"source identity drifted for {mapping_id}")
        span = origin["sourceSpan"]
        selected = source[span["startByte"] : span["endByte"]]
        require(source_fragment in selected, f"source span lost semantic owner for {mapping_id}")
        generated_span = mapping["generatedSpan"]
        require(
            0 <= generated_span["startByte"] < generated_span["endByte"] <= len(generated),
            f"invalid generated span for {mapping_id}",
        )

    require(
        document["traceAnchors"]
        == [
            {
                "generatedLine": 7,
                "mappingId": "stmt:sys-println:70:113",
                "selection": "emitter-runtime-line",
            }
        ],
        "runtime trace anchor drifted",
    )
    require(str(source_path.resolve().parent.parent.parent) not in map_path.read_text(encoding="utf-8"), "machine path leaked into map")
    print("reflaxe.php ordinary-Haxe tracer map passed")


if __name__ == "__main__":
    main()
