package reflaxe.php.map;

import haxe.crypto.Sha256;
import haxe.io.Bytes;
import reflaxe.php.ir.PhpSourceFile;
import reflaxe.php.ir.PhpSourceKind;
import reflaxe.php.ir.PhpSourcePosition;
import reflaxe.php.print.PhpRenderedFile;
import reflaxe.php.print.PhpRenderedMapping;

/** Deterministic serializer for authenticated generated-PHP range mappings. **/
class PhpRangeMapWriter {
	public final config:PhpRangeMapConfig;

	public function new(config:PhpRangeMapConfig) {
		if (config == null) {
			throw "PHP range-map writer requires configuration";
		}
		this.config = config;
	}

	public function write(rendered:PhpRenderedFile):String {
		if (rendered == null || rendered.source.length == 0 || rendered.source.indexOf("\r") != -1) {
			throw "PHP range-map writer requires non-empty LF-normalized generated bytes";
		}
		if (rendered.mappingCount == 0) {
			throw "PHP range-map writer requires at least one exact mapping";
		}

		final generatedBytes = Bytes.ofString(rendered.source);
		final mappings = [for (mapping in rendered.mappingIterator()) mapping];
		mappings.sort(compareMappings);
		validateMappings(mappings, generatedBytes);
		final sources = collectSources(mappings);
		final mappingRecords:Array<Dynamic> = [];
		final traceAnchors:Array<Dynamic> = [];
		final anchorLines:Map<Int, String> = [];
		for (mapping in mappings) {
			final sourceFile = requireSourceFile(mapping);
			mappingRecords.push({
				id: mapping.id,
				generatedSpan: span(generatedBytes, mapping.generatedStartByte, mapping.generatedEndByte),
				nodeKind: mapping.nodeKind,
				structuralDepth: mapping.structuralDepth,
				origin: {
					kind: sourceKind(sourceFile.kind),
					sourceId: sourceFile.id,
					sourceSpan: sourceSpan(mapping),
					semanticNodeId: mapping.semanticNodeId
				}
			});
			if (mapping.traceAnchor) {
				final line = PhpSourceFile.positionIn(generatedBytes, mapping.generatedStartByte).line;
				if (anchorLines.exists(line)) {
					throw "Duplicate PHP trace anchor on generated line " + line + ": " + anchorLines.get(line) + " and " + mapping.id;
				}
				anchorLines.set(line, mapping.id);
				traceAnchors.push({generatedLine: line, mappingId: mapping.id, selection: "emitter-runtime-line"});
			}
		}
		traceAnchors.sort((left, right) -> Reflect.compare(left.generatedLine, right.generatedLine));

		final document:Dynamic = {
			schemaVersion: 1,
			format: config.format,
			generator: {
				id: config.generatorId,
				version: config.generatorVersion,
				sourceSha256: config.generatorSourceSha256
			},
			buildInputsSha256: config.buildInputsSha256,
			coordinateSystem: {
				byteEncoding: "utf-8",
				byteRange: "half-open",
				lineBase: 1,
				columnBase: 0,
				columnEncoding: "utf-8-bytes"
			},
			generated: {
				path: rendered.path,
				sha256: Sha256.make(generatedBytes).toHex().toLowerCase(),
				byteLength: generatedBytes.length,
				lineCount: PhpSourceFile.countLines(generatedBytes),
				encoding: "utf-8",
				lineEndings: "lf"
			},
			sources: sources.map(source -> sourceRecord(source)),
			mappings: mappingRecords,
			traceAnchors: traceAnchors
		};
		return PhpCanonicalJson.encode(document);
	}

	static function collectSources(mappings:Array<PhpRenderedMapping>):Array<PhpSourceFile> {
		final byId:Map<String, PhpSourceFile> = [];
		for (mapping in mappings) {
			final source = requireSourceFile(mapping);
			if (byId.exists(source.id)) {
				final previous = byId.get(source.id);
				if (previous.rootId != source.rootId
					|| previous.path != source.path
					|| previous.kind != source.kind
					|| previous.sha256 != source.sha256
					|| previous.byteLength != source.byteLength) {
					throw "Conflicting PHP source identity: " + source.id;
				}
			} else {
				byId.set(source.id, source);
			}
		}
		final sources = [for (source in byId) source];
		sources.sort((left, right) -> Reflect.compare(left.id, right.id));
		return sources;
	}

	static function validateMappings(mappings:Array<PhpRenderedMapping>, generatedBytes:Bytes):Void {
		final ids:Map<String, Bool> = [];
		for (mapping in mappings) {
			if (mapping.generatedEndByte > generatedBytes.length) {
				throw "PHP mapping exceeds generated bytes: " + mapping.id;
			}
			PhpSourceFile.positionIn(generatedBytes, mapping.generatedStartByte);
			PhpSourceFile.positionIn(generatedBytes, mapping.generatedEndByte);
			if (ids.exists(mapping.id)) {
				throw "Duplicate PHP mapping ID: " + mapping.id;
			}
			ids.set(mapping.id, true);
		}
		for (leftIndex in 0...mappings.length) {
			final left = mappings[leftIndex];
			for (rightIndex in leftIndex + 1...mappings.length) {
				final right = mappings[rightIndex];
				if (right.generatedStartByte >= left.generatedEndByte) {
					break;
				}
				final leftContainsRight = left.generatedStartByte <= right.generatedStartByte
					&& left.generatedEndByte >= right.generatedEndByte;
				final rightContainsLeft = right.generatedStartByte <= left.generatedStartByte
					&& right.generatedEndByte >= left.generatedEndByte;
				if (!leftContainsRight && !rightContainsLeft) {
					throw "Crossing PHP mappings are invalid: " + left.id + " and " + right.id;
				}
				if (left.generatedStartByte == right.generatedStartByte
					&& left.generatedEndByte == right.generatedEndByte
					&& left.structuralDepth == right.structuralDepth) {
					throw "Ambiguous PHP mappings share a span and depth: " + left.id + " and " + right.id;
				}
			}
		}
	}

	static function compareMappings(left:PhpRenderedMapping, right:PhpRenderedMapping):Int {
		final start = Reflect.compare(left.generatedStartByte, right.generatedStartByte);
		if (start != 0) {
			return start;
		}
		final end = Reflect.compare(left.generatedEndByte, right.generatedEndByte);
		return end != 0 ? end : Reflect.compare(left.id, right.id);
	}

	static function requireSourceFile(mapping:PhpRenderedMapping):PhpSourceFile {
		if (mapping.source.sourceFile == null || mapping.source.startByte == null || mapping.source.endByte == null) {
			throw "PHP mapping lost its authenticated source: " + mapping.id;
		}
		return mapping.source.sourceFile;
	}

	static function sourceKind(kind:PhpSourceKind):String {
		return switch (kind) {
			case PhpHaxeSource: "haxe-source";
			case PhpNativeSource: "native-source";
		}
	}

	static function sourceRecord(source:PhpSourceFile):Dynamic {
		return {
			id: source.id,
			rootId: source.rootId,
			path: source.path,
			kind: switch (source.kind) {
				case PhpHaxeSource: "haxe";
				case PhpNativeSource: "native";
			},
			sha256: source.sha256,
			byteLength: source.byteLength,
			lineCount: source.lineCount
		};
	}

	static function sourceSpan(mapping:PhpRenderedMapping):Dynamic {
		final source = requireSourceFile(mapping);
		return span(Bytes.ofString(source.content), mapping.source.startByte, mapping.source.endByte);
	}

	static function span(bytes:Bytes, startByte:Int, endByte:Int):Dynamic {
		if (startByte < 0 || endByte <= startByte || endByte > bytes.length) {
			throw "PHP map span is not non-empty and in bounds";
		}
		return {
			startByte: startByte,
			endByte: endByte,
			start: position(PhpSourceFile.positionIn(bytes, startByte)),
			end: position(PhpSourceFile.positionIn(bytes, endByte))
		};
	}

	static function position(value:PhpSourcePosition):Dynamic {
		return {line: value.line, columnUtf8: value.columnUtf8};
	}
}
