package reflaxe.php.map;

import haxe.crypto.Sha256;
import haxe.io.Bytes;
import reflaxe.php.ir.PhpSourceFile;
import reflaxe.php.ir.PhpSourceKind;
import reflaxe.php.ir.PhpSourcePosition;
import reflaxe.php.map.PhpCanonicalJson.PhpJsonField;
import reflaxe.php.map.PhpCanonicalJson.PhpJsonValue;
import reflaxe.php.print.PhpRenderedFile;
import reflaxe.php.print.PhpRenderedMapping;

private typedef PhpTraceAnchor = {
	final generatedLine:Int;
	final mappingId:String;
	final selection:String;
}

/** Deterministic serializer for authenticated generated-PHP range mappings. **/
class PhpRangeMapWriter {
	public final config:PhpRangeMapConfig;

	public function new(config:PhpRangeMapConfig) {
		if (config == null) {
			throw "PHP range-map writer requires configuration";
		}
		this.config = config;
	}

	public function write(rendered:PhpRenderedFile):String {
		if (rendered == null || rendered.source.length == 0 || rendered.source.indexOf("\r") != -1) {
			throw "PHP range-map writer requires non-empty LF-normalized generated bytes";
		}
		if (rendered.mappingCount == 0) {
			throw "PHP range-map writer requires at least one exact mapping";
		}

		final generatedBytes = Bytes.ofString(rendered.source);
		final mappings = [for (mapping in rendered.mappingIterator()) mapping];
		mappings.sort(compareMappings);
		validateMappings(mappings, generatedBytes);
		final sources = collectSources(mappings);
		final mappingRecords:Array<PhpJsonValue> = [];
		final traceAnchors:Array<PhpTraceAnchor> = [];
		final anchorLines:Map<Int, String> = [];
		for (mapping in mappings) {
			final sourceFile = requireSourceFile(mapping);
			mappingRecords.push(object([
				field("id", text(mapping.id)),
				field("generatedSpan", span(generatedBytes, mapping.generatedStartByte, mapping.generatedEndByte)),
				field("nodeKind", text(mapping.nodeKind)),
				field("structuralDepth", integer(mapping.structuralDepth)),
				field("origin", object([
					field("kind", text(sourceKind(sourceFile.kind))),
					field("sourceId", text(sourceFile.id)),
					field("sourceSpan", sourceSpan(mapping)),
					field("semanticNodeId", text(mapping.semanticNodeId))
				]))
			]));
			if (mapping.traceAnchor) {
				final line = PhpSourceFile.positionIn(generatedBytes, mapping.generatedStartByte).line;
				if (anchorLines.exists(line)) {
					throw "Duplicate PHP trace anchor on generated line " + line + ": " + anchorLines.get(line) + " and " + mapping.id;
				}
				anchorLines.set(line, mapping.id);
				traceAnchors.push({generatedLine: line, mappingId: mapping.id, selection: "emitter-runtime-line"});
			}
		}
		traceAnchors.sort((left, right) -> compareInts(left.generatedLine, right.generatedLine));

		final document = object([
			field("schemaVersion", integer(1)),
			field("format", text(config.format)),
			field("generator", object([
				field("id", text(config.generatorId)),
				field("version", text(config.generatorVersion)),
				field("sourceSha256", text(config.generatorSourceSha256))
			])),
			field("buildInputsSha256", text(config.buildInputsSha256)),
			field("coordinateSystem", object([
				field("byteEncoding", text("utf-8")),
				field("byteRange", text("half-open")),
				field("lineBase", integer(1)),
				field("columnBase", integer(0)),
				field("columnEncoding", text("utf-8-bytes"))
			])),
			field("generated", object([
				field("path", text(rendered.path)),
				field("sha256", text(Sha256.make(generatedBytes).toHex().toLowerCase())),
				field("byteLength", integer(generatedBytes.length)),
				field("lineCount", integer(PhpSourceFile.countLines(generatedBytes))),
				field("encoding", text("utf-8")),
				field("lineEndings", text("lf"))
			])),
			field("sources", array(sources.map(sourceRecord))),
			field("mappings", array(mappingRecords)),
			field("traceAnchors", array([
				for (anchor in traceAnchors)
					object([
						field("generatedLine", integer(anchor.generatedLine)),
						field("mappingId", text(anchor.mappingId)),
						field("selection", text(anchor.selection))
					])
			]))
		]);
		return PhpCanonicalJson.encode(document);
	}

	static function collectSources(mappings:Array<PhpRenderedMapping>):Array<PhpSourceFile> {
		final byId:Map<String, PhpSourceFile> = [];
		for (mapping in mappings) {
			final source = requireSourceFile(mapping);
			if (byId.exists(source.id)) {
				final previous = byId.get(source.id);
				if (previous.rootId != source.rootId
					|| previous.path != source.path
					|| previous.kind != source.kind
					|| previous.sha256 != source.sha256
					|| previous.byteLength != source.byteLength) {
					throw "Conflicting PHP source identity: " + source.id;
				}
			} else {
				byId.set(source.id, source);
			}
		}
		final sources = [for (source in byId) source];
		sources.sort((left, right) -> compareText(left.id, right.id));
		return sources;
	}

	static function validateMappings(mappings:Array<PhpRenderedMapping>, generatedBytes:Bytes):Void {
		final ids:Map<String, Bool> = [];
		for (mapping in mappings) {
			if (mapping.generatedEndByte > generatedBytes.length) {
				throw "PHP mapping exceeds generated bytes: " + mapping.id;
			}
			PhpSourceFile.positionIn(generatedBytes, mapping.generatedStartByte);
			PhpSourceFile.positionIn(generatedBytes, mapping.generatedEndByte);
			if (ids.exists(mapping.id)) {
				throw "Duplicate PHP mapping ID: " + mapping.id;
			}
			ids.set(mapping.id, true);
		}
		for (leftIndex in 0...mappings.length) {
			final left = mappings[leftIndex];
			for (rightIndex in leftIndex + 1...mappings.length) {
				final right = mappings[rightIndex];
				if (right.generatedStartByte >= left.generatedEndByte) {
					break;
				}
				final leftContainsRight = left.generatedStartByte <= right.generatedStartByte
					&& left.generatedEndByte >= right.generatedEndByte;
				final rightContainsLeft = right.generatedStartByte <= left.generatedStartByte
					&& right.generatedEndByte >= left.generatedEndByte;
				if (!leftContainsRight && !rightContainsLeft) {
					throw "Crossing PHP mappings are invalid: " + left.id + " and " + right.id;
				}
				if (left.generatedStartByte == right.generatedStartByte
					&& left.generatedEndByte == right.generatedEndByte
					&& left.structuralDepth == right.structuralDepth) {
					throw "Ambiguous PHP mappings share a span and depth: " + left.id + " and " + right.id;
				}
			}
		}
	}

	static function compareMappings(left:PhpRenderedMapping, right:PhpRenderedMapping):Int {
		final start = compareInts(left.generatedStartByte, right.generatedStartByte);
		if (start != 0) {
			return start;
		}
		final end = compareInts(left.generatedEndByte, right.generatedEndByte);
		return end != 0 ? end : compareText(left.id, right.id);
	}

	static function requireSourceFile(mapping:PhpRenderedMapping):PhpSourceFile {
		if (mapping.source.sourceFile == null || mapping.source.startByte == null || mapping.source.endByte == null) {
			throw "PHP mapping lost its authenticated source: " + mapping.id;
		}
		return mapping.source.sourceFile;
	}

	static function sourceKind(kind:PhpSourceKind):String {
		return switch (kind) {
			case PhpHaxeSource: "haxe-source";
			case PhpNativeSource: "native-source";
		}
	}

	static function sourceRecord(source:PhpSourceFile):PhpJsonValue {
		return object([
			field("id", text(source.id)),
			field("rootId", text(source.rootId)),
			field("path", text(source.path)),
			field("kind", text(switch (source.kind) {
				case PhpHaxeSource: "haxe";
				case PhpNativeSource: "native";
			})),
			field("sha256", text(source.sha256)),
			field("byteLength", integer(source.byteLength)),
			field("lineCount", integer(source.lineCount))
		]);
	}

	static function sourceSpan(mapping:PhpRenderedMapping):PhpJsonValue {
		final source = requireSourceFile(mapping);
		return span(Bytes.ofString(source.content), mapping.source.startByte, mapping.source.endByte);
	}

	static function span(bytes:Bytes, startByte:Int, endByte:Int):PhpJsonValue {
		if (startByte < 0 || endByte <= startByte || endByte > bytes.length) {
			throw "PHP map span is not non-empty and in bounds";
		}
		return object([
			field("startByte", integer(startByte)),
			field("endByte", integer(endByte)),
			field("start", position(PhpSourceFile.positionIn(bytes, startByte))),
			field("end", position(PhpSourceFile.positionIn(bytes, endByte)))
		]);
	}

	static function position(value:PhpSourcePosition):PhpJsonValue {
		return object([
			field("line", integer(value.line)),
			field("columnUtf8", integer(value.columnUtf8))
		]);
	}

	static inline function field(name:String, value:PhpJsonValue):PhpJsonField {
		return {name: name, value: value};
	}

	static inline function object(fields:Array<PhpJsonField>):PhpJsonValue {
		return ObjectValue(fields);
	}

	static inline function array(values:Array<PhpJsonValue>):PhpJsonValue {
		return ArrayValue(values);
	}

	static inline function text(value:String):PhpJsonValue {
		return StringValue(value);
	}

	static inline function integer(value:Int):PhpJsonValue {
		return IntegerValue(value);
	}

	static function compareInts(left:Int, right:Int):Int {
		return left < right ? -1 : left > right ? 1 : 0;
	}

	static function compareText(left:String, right:String):Int {
		return left < right ? -1 : left > right ? 1 : 0;
	}
}
