<?php
/**
 * Independent native WordPress 7.0 oracle for SDK-060 metadata.
 *
 * This file is deliberately not generated by the compiler under test. Product
 * registration and render adapters are Haxe-authored; this external consumer
 * catches shared compiler/projection mistakes by observing WordPress directly.
 */

if ( 2 !== $argc ) {
	fwrite( STDERR, "usage: native-wordpress-oracle.php <generated-block-root>\n" );
	exit( 2 );
}

$generated_root = $argv[1];
if ( ! str_starts_with( $generated_root, '/var/www/html/wp-content/plugins/' ) ) {
	throw new InvalidArgumentException( 'Generated block root is outside the plugin directory.' );
}

define( 'WP_USE_THEMES', false );
require '/var/www/html/wp-load.php';

$registered = array();
foreach ( array( 'book-grid', 'callout' ) as $slug ) {
	$metadata_root = $generated_root . '/blocks/' . $slug;
	if ( ! is_file( $metadata_root . '/block.json' ) ) {
		throw new RuntimeException( 'Generated block metadata is absent for ' . $slug );
	}
	$block = register_block_type( $metadata_root );
	if ( false === $block ) {
		throw new RuntimeException( 'Native metadata registration failed for ' . $slug );
	}
	$registered[ $block->name ] = array(
		'apiVersion'          => $block->api_version,
		'attributeNames'      => array_keys( $block->attributes ),
		'category'            => $block->category,
		'editorScriptHandles' => $block->editor_script_handles,
		'hasRenderCallback'   => is_callable( $block->render_callback ),
		'scriptHandles'       => $block->script_handles,
		'styleHandles'        => $block->style_handles,
		'title'               => $block->title,
	);
}

$registry = WP_Block_Type_Registry::get_instance();
foreach ( array_keys( $registered ) as $name ) {
	if ( ! $registry->is_registered( $name ) ) {
		throw new RuntimeException( 'Native registry omitted ' . $name );
	}
}

$rendered = render_block(
	array(
		'blockName'    => 'wordpresshx/book-grid',
		'attrs'        => array( 'count' => 3, 'showCover' => true ),
		'innerBlocks'  => array(),
		'innerHTML'    => '',
		'innerContent' => array(),
	)
);
if ( '<div class="wp-block-wordpresshx-book-grid"></div>' !== $rendered ) {
	throw new RuntimeException( 'Dynamic block render file was not consumed by WordPress.' );
}

global $wp_version;
echo wp_json_encode(
	array(
		'check'            => 'wordpresshx-sdk060-native-block-metadata-v1',
		'dynamicRendered'  => true,
		'phpVersion'       => PHP_VERSION,
		'profileId'        => 'wp70-release',
		'registeredBlocks' => $registered,
		'wordpressVersion' => $wp_version,
	),
	JSON_UNESCAPED_SLASHES
);
