package wordpresshx.cli.project;

import wordpresshx.cli.CliFailure;
import wordpresshx.cli.ownership.OwnershipContract;
import wordpresshx.cli.ownership.OwnershipContract.OwnershipManifest;
import wordpresshx.cli.ownership.OwnershipFailure;
import wordpresshx.cli.ownership.OwnershipJson;

/** Read-only proof that current generated bytes still match their exact manifest. **/
class OwnershipPreflight {
	public static function inspect(context:ProjectContext):Null<OwnershipManifest> {
		final bootstrap = context.bootstrap;
		final paths = OwnershipPaths.resolve(bootstrap);
		final lockPath = paths.layout.transactionRoot + "/lock";
		final journalPath = paths.layout.transactionRoot + "/journal.json";
		final temporaryPath = paths.layout.transactionRoot + "/.journal.json.tmp";
		for (relative in [lockPath, journalPath, temporaryPath]) {
			if (ProjectFiles.exists(bootstrap.root, relative)) {
				throw new CliFailure("WPHX1030", "an ownership transaction requires exact recovery before this no-write command can continue", 5,
					"ownership-publish", relative, ["Run wphx build or wphx clean to perform journal-bound recovery, then retry."]);
			}
		}
		if (!ProjectFiles.exists(bootstrap.root, paths.layout.manifestPath)) {
			return null;
		}
		try {
			final manifest = OwnershipContract.validateManifest(OwnershipJson.parseCanonical(ProjectFiles.read(bootstrap.root, paths.layout.manifestPath,
				"ownership manifest", "ownership-publish"), "ownership manifest"));
			if (manifest.locations.manifestPath != paths.layout.manifestPath
				|| manifest.locations.transactionRoot != paths.layout.transactionRoot) {
				throw new CliFailure("WPHX1031", "ownership manifest uses a different reserved layout", 5, "ownership-publish", paths.layout.manifestPath, [
					"Do not move generated ownership metadata; clean with its matching CLI before changing output roots."
				]);
			}
			if (!rootsMatch(manifest, bootstrap, paths)) {
				throw new CliFailure("WPHX1031", "ownership manifest output roots differ from wordpress-hx.json", 5, "ownership-publish",
					paths.layout.manifestPath, [
						"Restore the matching configuration or clean before an explicit output-root migration."
					]);
			}
			for (file in manifest.files) {
				final relative = file.path;
				final bytes = ProjectFiles.read(bootstrap.root, relative, "owned generated file", "ownership-publish");
				if (bytes.length != file.sizeBytes || OwnershipJson.digest(bytes) != file.contentSha256) {
					throw new CliFailure("WPHX1032", "owned generated bytes differ from the manifest", 5, "ownership-publish", relative,
						["Revert the generated edit, or explicitly adopt the file before rebuilding."]);
				}
			}
			return manifest;
		} catch (failure:CliFailure) {
			throw failure;
		} catch (failure:OwnershipFailure) {
			throw new CliFailure("WPHX1031", failure.message, 5, "ownership-publish", failure.relativePath, [
				"Restore the exact generated bytes and manifest or diagnose the ownership transaction before retrying."
			]);
		}
	}

	static function rootsMatch(manifest:OwnershipManifest, bootstrap:ProjectBootstrap, paths:ProjectOwnershipPaths):Bool {
		final expected = new Map<String, String>();
		for (root in bootstrap.outputRoots) {
			expected.set(root.id, root.path);
		}
		expected.set(paths.distributionRootId, bootstrap.distributionRoot);
		if (manifest.outputRoots.length > expectedCount(expected)) {
			return false;
		}
		for (root in manifest.outputRoots) {
			if (expected.get(root.rootId) != root.path) {
				return false;
			}
		}
		return true;
	}

	static function expectedCount(values:Map<String, String>):Int {
		var count = 0;
		for (_ => _ in values) {
			count++;
		}
		return count;
	}
}
