package wordpresshx.cli.project;

import wordpresshx.cli.CliFailure;
import wordpresshx.cli.ownership.OwnershipContract;
import wordpresshx.cli.ownership.OwnershipFailure;
import wordpresshx.cli.ownership.OwnershipJson;

/** Read-only proof that current generated bytes still match their exact manifest. **/
class OwnershipPreflight {
	public static function inspect(context:ProjectContext):Null<Dynamic> {
		final bootstrap = context.bootstrap;
		final paths = OwnershipPaths.resolve(bootstrap);
		final lockPath = paths.layout.transactionRoot + "/lock";
		final journalPath = paths.layout.transactionRoot + "/journal.json";
		final temporaryPath = paths.layout.transactionRoot + "/.journal.json.tmp";
		for (relative in [lockPath, journalPath, temporaryPath]) {
			if (ProjectFiles.exists(bootstrap.root, relative)) {
				throw new CliFailure("WPHX1030", "an ownership transaction requires exact recovery before this no-write command can continue", 5,
					"ownership-publish", relative, ["Run wphx build or wphx clean to perform journal-bound recovery, then retry."]);
			}
		}
		if (!ProjectFiles.exists(bootstrap.root, paths.layout.manifestPath)) {
			return null;
		}
		try {
			final manifest = OwnershipJson.parseCanonical(ProjectFiles.read(bootstrap.root, paths.layout.manifestPath, "ownership manifest",
				"ownership-publish"), "ownership manifest");
			OwnershipContract.validateManifest(manifest);
			final locations = OwnershipContract.fieldObject(manifest, "locations", "manifest");
			if (OwnershipContract.string(locations, "manifestPath", "manifest locations") != paths.layout.manifestPath
				|| OwnershipContract.string(locations, "transactionRoot", "manifest locations") != paths.layout.transactionRoot) {
				throw new CliFailure("WPHX1031", "ownership manifest uses a different reserved layout", 5, "ownership-publish", paths.layout.manifestPath, [
					"Do not move generated ownership metadata; clean with its matching CLI before changing output roots."
				]);
			}
			final expectedRoots:Array<Dynamic> = [
				for (root in bootstrap.outputRoots)
					OwnershipJson.object([
						"rootId" => root.id,
						"path" => root.path,
						"ownershipMode" => "exact-file-manifest-coexists-with-unowned"
					])
			];
			expectedRoots.sort((left, right) -> {
				final leftKey = Reflect.field(left, "path") + "\x00" + Reflect.field(left, "rootId");
				final rightKey = Reflect.field(right, "path") + "\x00" + Reflect.field(right, "rootId");
				return Reflect.compare(leftKey, rightKey);
			});
			if (OwnershipJson.encode(Reflect.field(manifest, "outputRoots")) != OwnershipJson.encode(expectedRoots)) {
				throw new CliFailure("WPHX1031", "ownership manifest output roots differ from wordpress-hx.json", 5, "ownership-publish",
					paths.layout.manifestPath, [
						"Restore the matching configuration or clean before an explicit output-root migration."
					]);
			}
			for (file in OwnershipContract.array(manifest, "files", "manifest")) {
				final relative = OwnershipContract.string(file, "path", "manifest file");
				final bytes = ProjectFiles.read(bootstrap.root, relative, "owned generated file", "ownership-publish");
				if (bytes.length != OwnershipContract.integer(file, "sizeBytes", "manifest file")
					|| OwnershipJson.digest(bytes) != OwnershipContract.string(file, "contentSha256", "manifest file")) {
					throw new CliFailure("WPHX1032", "owned generated bytes differ from the manifest", 5, "ownership-publish", relative,
						["Revert the generated edit, or explicitly adopt the file before rebuilding."]);
				}
			}
			return manifest;
		} catch (failure:CliFailure) {
			throw failure;
		} catch (failure:OwnershipFailure) {
			throw new CliFailure("WPHX1031", failure.message, 5, "ownership-publish", failure.relativePath, [
				"Restore the exact generated bytes and manifest or diagnose the ownership transaction before retrying."
			]);
		}
	}
}
