package wordpresshx.cli.project.development;

/** Private development-only WordPress installer and plugin activator. */
class WordPressBootstrapAdapter {
	public static function source():String {
		return [
			"<?php",
			"declare(strict_types=1);",
			"",
			"$wordpresshx_site_url = getenv('WPHX_INTERNAL_WORDPRESS_SITE_URL');",
			"$wordpresshx_site_title = getenv('WPHX_INTERNAL_WORDPRESS_SITE_TITLE');",
			"$wordpresshx_admin_password = getenv('WPHX_INTERNAL_WORDPRESS_ADMIN_PASSWORD');",
			"$wordpresshx_plugin = getenv('WPHX_INTERNAL_WORDPRESS_PLUGIN_ENTRY');",
			"if (!is_string($wordpresshx_site_url) || filter_var($wordpresshx_site_url, FILTER_VALIDATE_URL) === false",
			"	|| !is_string($wordpresshx_site_title) || $wordpresshx_site_title === ''",
			"	|| !is_string($wordpresshx_admin_password) || strlen($wordpresshx_admin_password) < 32",
			"	|| !is_string($wordpresshx_plugin) || preg_match('/^[a-z0-9]+(?:-[a-z0-9]+)*\\/[a-z0-9]+(?:-[a-z0-9]+)*\\.php$/D', $wordpresshx_plugin) !== 1) {",
			"	throw new RuntimeException('invalid private WordPressHx development bootstrap input');",
			"}",
			"",
			"$wordpresshx_url = parse_url($wordpresshx_site_url);",
			"if (!is_array($wordpresshx_url) || !isset($wordpresshx_url['host'], $wordpresshx_url['port'])) {",
			"	throw new RuntimeException('invalid private WordPressHx development site URL');",
			"}",
			"$_SERVER['HTTP_HOST'] = $wordpresshx_url['host'] . ':' . (string) $wordpresshx_url['port'];",
			"$_SERVER['HTTPS'] = 'off';",
			"$_SERVER['REQUEST_URI'] = '/';",
			"$_SERVER['SERVER_NAME'] = (string) $wordpresshx_url['host'];",
			"$_SERVER['SERVER_PORT'] = (string) $wordpresshx_url['port'];",
			"$_SERVER['SERVER_PROTOCOL'] = 'HTTP/1.1';",
			"",
			"$wordpresshx_required_files = [",
			"	'/var/www/html/wp-load.php',",
			"	'/var/www/html/wp-config.php',",
			"	'/var/www/html/wp-settings.php',",
			"	'/var/www/html/wp-includes/version.php',",
			"	'/var/www/html/wp-admin/includes/upgrade.php',",
			"	'/var/www/html/wp-admin/includes/plugin.php',",
			"	'/var/www/html/wp-content/plugins/' . $wordpresshx_plugin,",
			"];",
			"$wordpresshx_deadline = microtime(true) + 120.0;",
			"while (true) {",
			"	$wordpresshx_complete = true;",
			"	foreach ($wordpresshx_required_files as $wordpresshx_required_file) {",
			"		if (!is_file($wordpresshx_required_file)) {",
			"			$wordpresshx_complete = false;",
			"			break;",
			"		}",
			"	}",
			"	if ($wordpresshx_complete) {",
			"		break;",
			"	}",
			"	if (microtime(true) >= $wordpresshx_deadline) {",
			"		throw new RuntimeException('WordPress distribution did not become available');",
			"	}",
			"	usleep(100000);",
			"}",
			"",
			"define('WP_INSTALLING', true);",
			"require_once '/var/www/html/wp-load.php';",
			"require_once ABSPATH . 'wp-admin/includes/upgrade.php';",
			"require_once ABSPATH . 'wp-admin/includes/plugin.php';",
			"add_filter('pre_wp_mail', static function () { return true; });",
			"if (!is_blog_installed()) {",
			"	wp_install($wordpresshx_site_title, 'wordpresshx_admin', 'wordpresshx@example.invalid', false, '', $wordpresshx_admin_password);",
			"}",
			"update_option('home', $wordpresshx_site_url, false);",
			"update_option('siteurl', $wordpresshx_site_url, false);",
			"$wordpresshx_result = activate_plugin($wordpresshx_plugin, '', false, false);",
			"if (is_wp_error($wordpresshx_result)) {",
			"	throw new RuntimeException('generated plugin activation failed: ' . $wordpresshx_result->get_error_code());",
			"}",
			"if (!is_plugin_active($wordpresshx_plugin)) {",
			"	throw new RuntimeException('generated plugin was not active after activation');",
			"}",
			"fwrite(STDOUT, \"WORDPRESSHX_DEV_READY\\n\");",
			"while (true) { sleep(3600); }",
			""
		].join("\n");
	}
}
