package wordpresshx;

#if macro
import haxe.Json;
import haxe.macro.Context;
import haxe.macro.Expr;
import sys.io.File;
#end

/** Optional metadata; identity and compatibility requirements are derived. */
typedef PluginOptions = {
	@:optional final name:String;
	@:optional final description:String;
	@:optional final version:String;
	@:optional final author:String;
	@:optional final license:String;
	@:optional final namespace:String;
}

enum abstract WordPressTarget(String) {
	final Plugin = "plugin";
}

typedef PluginDefinition = {
	final target:WordPressTarget;
}

#if macro
private typedef CollectedPlugin = {
	final slug:String;
	final profile:String;
	final name:String;
	final description:String;
	final version:String;
	final author:String;
	final license:String;
	final namespace:String;
	final sourcePath:String;
	final startLine:Int;
	final startColumn:Int;
	final endLine:Int;
	final endColumn:Int;
}
#end

/** Haxe-first WordPress declarations collected at compile time. */
final class WordPress {
	#if macro
	static var collected:Null<CollectedPlugin>;
	static var writerRegistered = false;
	#end

	/**
		Declare the project as an ordinary WordPress plugin. The zero-argument
		form derives every conventional value from the scaffold identity.
	**/
	public static macro function plugin(?options:ExprOf<PluginOptions>):ExprOf<PluginDefinition> {
		final position = Context.currentPos();
		if (collected != null) {
			Context.error("A project may declare exactly one WordPress plugin", position);
		}
		final slug = requiredDefine("wordpress-hx-project-id", position);
		final profile = requiredDefine("wordpress-hx-profile", position);
		if (profile != "wp70-release") {
			Context.error("WordPress.plugin requires the exact wp70-release profile", position);
		}
		if (!~/^[a-z0-9]+(?:-[a-z0-9]+)*$/.match(slug)) {
			Context.error("WordPress.plugin requires a lowercase portable project slug", position);
		}

		final displayName = display(slug);
		final values = [
			"name" => displayName,
			"description" => displayName + " generated by WordPressHx.",
			"version" => "0.0.0",
			"author" => "WordPressHx project",
			"license" => "GPL-2.0-or-later",
			"namespace" => phpNamespace(slug)
		];
		if (options != null) {
			readOptions(options, values);
		}
		validate(values, position);
		final location = sourceLocation(position);
		collected = {
			slug: slug,
			profile: profile,
			name: required(values, "name", position),
			description: required(values, "description", position),
			version: required(values, "version", position),
			author: required(values, "author", position),
			license: required(values, "license", position),
			namespace: required(values, "namespace", position),
			sourcePath: location.path,
			startLine: location.startLine,
			startColumn: location.startColumn,
			endLine: location.endLine,
			endColumn: location.endColumn
		};
		registerWriter(position);
		return macro({target: wordpresshx.WordPress.WordPressTarget.Plugin} : wordpresshx.WordPress.PluginDefinition);
	}

	#if macro
	static function readOptions(options:ExprOf<PluginOptions>, values:Map<String, String>):Void {
		switch options.expr {
			case EObjectDecl(fields):
				for (field in fields) {
					if (!values.exists(field.field)) {
						Context.error("Unknown WordPress.plugin option " + field.field, field.expr.pos);
					}
					final value = switch field.expr.expr {
						case EConst(CString(source, _)): source;
						case _: Context.error("WordPress.plugin options must be literal strings", field.expr.pos);
					};
					values.set(field.field, value);
				}
			case EConst(CIdent("null")):
			case _:
				Context.error("WordPress.plugin options must be an inline typed object", options.pos);
		}
	}

	static function validate(values:Map<String, String>, position:Position):Void {
		for (name in ["name", "description", "author", "license"]) {
			printableHeader(required(values, name, position), name, position);
		}
		final version = required(values, "version", position);
		if (!~/^[0-9]+\.[0-9]+\.[0-9]+(?:-[0-9A-Za-z.-]+)?$/.match(version)) {
			Context.error("WordPress.plugin version must be an exact semantic version", position);
		}
		final namespace = required(values, "namespace", position);
		if (!~/^[A-Z_][A-Za-z0-9_]*(?:\\[A-Z_][A-Za-z0-9_]*)*$/.match(namespace)) {
			Context.error("WordPress.plugin namespace must be a relative PHP namespace", position);
		}
	}

	static function printableHeader(value:String, label:String, position:Position):Void {
		if (StringTools.trim(value) != value || value.length == 0 || value.indexOf("*/") >= 0) {
			Context.error("WordPress.plugin " + label + " is not a safe header value", position);
		}
		for (index in 0...value.length) {
			final code = value.charCodeAt(index);
			if (code < 0x20 || code > 0x7e) {
				Context.error("WordPress.plugin " + label + " must use printable ASCII in the current profile", position);
			}
		}
	}

	static function registerWriter(position:Position):Void {
		if (writerRegistered) {
			return;
		}
		writerRegistered = true;
		Context.onAfterTyping(_ -> {
			final plugin = collected;
			if (plugin == null) {
				Context.error("WordPress.plugin collection completed without a definition", position);
			}
			final output = requiredDefine("wordpress-hx-plan-output", position);
			File.saveContent(output, encode(plugin) + "\n");
		});
	}

	static function encode(plugin:CollectedPlugin):String {
		return "{" + '"author":' + Json.stringify(plugin.author) + ',"description":' + Json.stringify(plugin.description) + ',"endColumn":'
			+ plugin.endColumn + ',"endLine":' + plugin.endLine + ',"kind":"plugin"' + ',"license":' + Json.stringify(plugin.license) + ',"name":'
			+ Json.stringify(plugin.name) + ',"namespace":' + Json.stringify(plugin.namespace) + ',"profile":' + Json.stringify(plugin.profile)
			+ ',"schema":"wordpress-hx.plugin-plan.v1"' + ',"slug":' + Json.stringify(plugin.slug) + ',"sourcePath":'
			+ Json.stringify(plugin.sourcePath.split("\\").join("/")) + ',"startColumn":' + plugin.startColumn + ',"startLine":' + plugin.startLine
			+ ',"version":' + Json.stringify(plugin.version) + "}";
	}

	static function sourceLocation(position:Position):{
		path:String,
		startLine:Int,
		startColumn:Int,
		endLine:Int,
		endColumn:Int
	} {
		final info = Context.getPosInfos(position);
		final source = File.getContent(info.file);
		final start = lineColumn(source, info.min);
		final end = lineColumn(source, info.max);
		return {
			path: info.file,
			startLine: start.line,
			startColumn: start.column,
			endLine: end.line,
			endColumn: end.column
		};
	}

	static function lineColumn(source:String, offset:Int):{line:Int, column:Int} {
		var line = 1;
		var column = 1;
		final bounded = offset < 0 ? 0 : offset > source.length ? source.length : offset;
		for (index in 0...bounded) {
			if (source.charCodeAt(index) == 10) {
				line++;
				column = 1;
			} else {
				column++;
			}
		}
		return {line: line, column: column};
	}

	static function display(slug:String):String {
		return [for (part in slug.split("-")) upperFirst(part)].join(" ");
	}

	static function phpNamespace(slug:String):String {
		return [for (part in slug.split("-")) phpSegment(part)].join("\\");
	}

	static function phpSegment(value:String):String {
		final prefixed = value.charCodeAt(0) >= 48 && value.charCodeAt(0) <= 57 ? "P" + value : value;
		return upperFirst(prefixed);
	}

	static function upperFirst(value:String):String {
		return value.substr(0, 1).toUpperCase() + value.substr(1);
	}

	static function requiredDefine(name:String, position:Position):String {
		final value = Context.definedValue(name);
		if (value == null || value.length == 0) {
			Context.error("WordPressHx compiler define is missing: " + name, position);
		}
		return value;
	}

	static function required(values:Map<String, String>, name:String, position:Position):String {
		final value = values.get(name);
		if (value == null) {
			Context.error("WordPress.plugin option is missing: " + name, position);
		}
		return value;
	}
	#end
}
