package wordpresshx.cli.generatedoutput;

import wordpresshx.cli.CliFailure;
import wordpresshx.cli.closedjson.JsonDocument;
import wordpresshx.cli.closedjson.JsonReader;
import wordpresshx.cli.project.OwnershipPaths;
import wordpresshx.cli.project.ProjectBootstrap;
import wordpresshx.cli.project.ProjectContext;
import wordpresshx.cli.project.ProjectLoader;

/** Typed generated-output view over the established project loader. */
class GeneratedOutputProject {
	public final context:ProjectContext;
	public final projectId:String;
	public final metadataRoot:GeneratedOutputRoot;

	public static function load(start:String):GeneratedOutputProject {
		final bootstrap = ProjectLoader.discover(start);
		final context = ProjectLoader.resolve(bootstrap);
		final config = JsonReader.from(JsonDocument.parse(bootstrap.configBytes, "wordpress-hx.json", "WPHX3411"), "project configuration", "WPHX3411");
		final projectId = config.string("projectId", "WPHX3411");
		final paths = OwnershipPaths.resolve(bootstrap);
		final metadata = configuredRoot(bootstrap, paths.metadataRootId);
		return new GeneratedOutputProject(context, projectId, metadata);
	}

	public function select(ids:Array<String>):Array<GeneratedOutputRoot> {
		final selected:Array<GeneratedOutputRoot> = [];
		for (id in ids) {
			selected.push(configuredRoot(context.bootstrap, id));
		}
		selected.sort(compareRootId);
		if (!containsRoot(selected, metadataRoot.id)) {
			throw new CliFailure("WPHX3412", "committed output must include the metadata root containing the exact generated-files manifest", 5,
				"generated-output-policy", "wordpress-hx.json", [
					"Add --root " + metadataRoot.id + " so the manifest and selected generated bytes travel together."
				]);
		}
		return selected;
	}

	public function validatePolicy(policy:GeneratedOutputPolicy):Void {
		if (policy.projectId != projectId) {
			mismatch("policy project ID differs from wordpress-hx.json");
		}
		final selected:Array<GeneratedOutputRoot> = [];
		for (root in policy.roots) {
			final configured = configuredRoot(context.bootstrap, root.id);
			if (configured.path != root.path) {
				mismatch("policy output-root path differs from wordpress-hx.json");
			}
			selected.push(configured);
		}
		if (!containsRoot(selected, metadataRoot.id)) {
			mismatch("policy omits the manifest-bearing metadata root");
		}
	}

	public function unselectedRoots(selected:Array<GeneratedOutputRoot>):Array<GeneratedOutputRoot> {
		final result:Array<GeneratedOutputRoot> = [];
		for (root in context.bootstrap.outputRoots) {
			if (!containsRoot(selected, root.id)) {
				result.push(new GeneratedOutputRoot(root.id, root.path));
			}
		}
		result.sort(compareRootId);
		return result;
	}

	static function configuredRoot(bootstrap:ProjectBootstrap, id:String):GeneratedOutputRoot {
		for (root in bootstrap.outputRoots) {
			if (root.id == id) {
				return new GeneratedOutputRoot(root.id, root.path);
			}
		}
		throw new CliFailure("WPHX3412", "generated-output root ID is not declared by wordpress-hx.json: " + id, 5, "generated-output-policy",
			"wordpress-hx.json", [
				"Choose an exact ID from paths.outputRoots; root discovery is never inferred from files."
			]);
	}

	static function containsRoot(roots:Array<GeneratedOutputRoot>, id:String):Bool {
		for (root in roots) {
			if (root.id == id) {
				return true;
			}
		}
		return false;
	}

	static function compareRootId(left:GeneratedOutputRoot, right:GeneratedOutputRoot):Int {
		return left.id < right.id ? -1 : left.id > right.id ? 1 : 0;
	}

	static function mismatch<T>(message:String):T {
		throw new CliFailure("WPHX3412", message, 5, "generated-output-policy", GeneratedOutputPolicy.PATH, [
			"Restore the committed configuration and policy pair; changing admitted roots requires a newly reviewed enablement."
		]);
	}

	function new(context:ProjectContext, projectId:String, metadataRoot:GeneratedOutputRoot) {
		this.context = context;
		this.projectId = projectId;
		this.metadataRoot = metadataRoot;
	}
}
