import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import { createHash } from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import process from "node:process";
import { pathToFileURL } from "node:url";

import userEvent from "@testing-library/user-event";
import axe from "axe-core";
import { build } from "esbuild";
import { JSDOM } from "jsdom";
import ts from "typescript";

const [packageRoot, workRoot, replayRoot] = process.argv.slice(2);
assert.ok(packageRoot, "package root is required");
assert.ok(workRoot, "first generated root is required");
assert.ok(replayRoot, "replay generated root is required");

const toolingRoot = path.dirname(new URL(import.meta.url).pathname);
const nodeModules = path.join(toolingRoot, "node_modules");
const profilePath = path.join(
  packageRoot,
  "src/wordpress/hx/gutenberg/profile/wp70-release.browser-hxx.json"
);
const fixtureSource = path.join(
  packageRoot,
  "test/hxx-fixture/src/sdk032/fixture/Main.hx"
);
const runtimeEntrySource = path.join(toolingRoot, "runtime-entry.tsx");
const visualEntrySource = path.join(toolingRoot, "visual-entry.tsx");
const visualHtmlSource = path.join(packageRoot, "test/hxx-runtime/index.html");

assert.equal(process.version, "v22.17.0", "unexpected Node runtime");
assert.equal(
  execFileSync("npm", ["--version"], { encoding: "utf8" }).trim(),
  "10.9.2",
  "unexpected npm runtime"
);
assert.equal(ts.version, "5.9.3", "unexpected TypeScript runtime");
assert.ok(fs.existsSync(runtimeEntrySource), "runtime entry was not staged");
assert.ok(fs.existsSync(visualEntrySource), "visual entry was not staged");
const visualHtml = fs.readFileSync(visualHtmlSource, "utf8");
for (const requiredHtml of [
  '<div id="root"></div>',
  '<link rel="stylesheet" href="./proof.css" />',
  '<script type="module" src="./proof.js"></script>',
]) {
  assert.ok(visualHtml.includes(requiredHtml), `visual HTML is missing ${requiredHtml}`);
}

function readJson(file) {
  return JSON.parse(fs.readFileSync(file, "utf8"));
}

function sha256(value) {
  return createHash("sha256").update(value).digest("hex");
}

function walkFiles(root) {
  const output = [];
  for (const entry of fs.readdirSync(root, { withFileTypes: true })) {
    if (entry.name === "node_modules" || entry.name === "runtime") {
      continue;
    }
    const fullPath = path.join(root, entry.name);
    if (entry.isDirectory()) {
      output.push(...walkFiles(fullPath));
    } else if (entry.isFile()) {
      output.push(fullPath);
    }
  }
  return output.sort();
}

function relativeTree(root) {
  return new Map(
    walkFiles(root).map((file) => [
      path.relative(root, file).split(path.sep).join("/"),
      fs.readFileSync(file),
    ])
  );
}

function assertSameTree(firstRoot, secondRoot) {
  const first = relativeTree(firstRoot);
  const second = relativeTree(secondRoot);
  assert.deepEqual([...first.keys()], [...second.keys()], "generated file set drift");
  for (const [relativePath, content] of first) {
    assert.deepEqual(
      content,
      second.get(relativePath),
      `generated bytes drifted for ${relativePath}`
    );
  }
}

function assertNoMachinePath(label, text) {
  const slash = "/";
  const backslash = "\\";
  for (const forbidden of [
    [slash, "Users", slash].join(""),
    [slash, "home", slash, "runner", slash].join(""),
    [backslash, "Users", backslash].join(""),
    "wordpresshx-sdk032-build.",
    "wordpresshx-sdk032-replay.",
  ]) {
    assert.ok(!text.includes(forbidden), `${label} leaks machine path ${forbidden}`);
  }
}

assertSameTree(workRoot, replayRoot);
for (const [relativePath, content] of relativeTree(workRoot)) {
  assertNoMachinePath(relativePath, content.toString("utf8"));
}

const profile = readJson(profilePath);
assert.equal(profile.schemaVersion, 1);
assert.equal(profile.profileId, "wp70-release");
assert.equal(profile.provider.wordpressVersion, "7.0.0");
assert.equal(
  profile.provider.gutenbergCommit,
  "a2a354cf35e5b69c3330d6c1cfd42d8dc2efb9fd"
);
assert.deepEqual(profile.provider.dependencyLock, {
  path: "package-lock.json",
  blob: "b45618b56375df75595ba7184f688cebf41795f8",
  sha256: "48a76d63400289c1e80ca9685651157fd49d7eded233a68cb19ced59f78cc9ee",
});
assert.equal(profile.react.runtimeVersion, "18.3.1");
assert.equal(profile.react.typesVersion, "18.3.27");
assert.deepEqual(
  profile.components.map(({ tag, request, export: exportName }) => ({
    tag,
    request,
    exportName,
  })),
  [
    {
      tag: "Button",
      request: "@wordpress/components",
      exportName: "Button",
    },
    {
      tag: "Notice",
      request: "@wordpress/components",
      exportName: "Notice",
    },
  ]
);
assert.deepEqual(profile.hooks, [
  "createContext",
  "useContext",
  "useEffect",
  "useRef",
  "useState",
]);
assert.deepEqual(profile.policy, {
  rawJsxAllowed: false,
  browserHxxRuntimeAllowed: false,
  openAttributeSpreadsAllowed: false,
  profileGeneratedOrCurated: "curated-exact-source-and-published-types",
});

const toolingManifest = readJson(path.join(toolingRoot, "package.json"));
const toolingLock = readJson(path.join(toolingRoot, "package-lock.json"));
assert.equal(toolingManifest.private, true);
assert.equal(toolingManifest.packageManager, "npm@10.9.2");
assert.deepEqual(toolingManifest.engines, {
  node: "22.17.0",
  npm: "10.9.2",
});
assert.equal(toolingLock.lockfileVersion, 3);
assert.equal(toolingLock.requires, true);
assert.deepEqual(
  toolingLock.packages[""].devDependencies,
  toolingManifest.devDependencies
);

const exactWordPressPackages = {
  "@wordpress/a11y": "4.40.0",
  "@wordpress/base-styles": "6.16.0",
  "@wordpress/components": "32.2.0",
  "@wordpress/compose": "7.40.0",
  "@wordpress/data": "10.40.0",
  "@wordpress/date": "5.40.0",
  "@wordpress/deprecated": "4.40.0",
  "@wordpress/dom": "4.40.0",
  "@wordpress/dom-ready": "4.40.0",
  "@wordpress/element": "6.40.0",
  "@wordpress/escape-html": "3.40.0",
  "@wordpress/hooks": "4.40.0",
  "@wordpress/html-entities": "4.40.0",
  "@wordpress/i18n": "6.13.0",
  "@wordpress/icons": "11.7.0",
  "@wordpress/is-shallow-equal": "5.40.0",
  "@wordpress/keycodes": "4.40.0",
  "@wordpress/primitives": "4.40.0",
  "@wordpress/priority-queue": "3.40.0",
  "@wordpress/private-apis": "1.40.0",
  "@wordpress/redux-routine": "5.40.0",
  "@wordpress/rich-text": "7.40.0",
  "@wordpress/undo-manager": "1.40.0",
  "@wordpress/warning": "3.40.0",
};
assert.deepEqual(toolingManifest.overrides, {
  "@ariakit/react": "0.4.21",
  ...Object.fromEntries(
    Object.entries(exactWordPressPackages).filter(
      ([name]) => name !== "@wordpress/components" && name !== "@wordpress/element"
    )
  ),
});

const npmIntegrity = /^sha512-[A-Za-z0-9+/]+={0,2}$/;
const seenWordPressPackages = new Set();
for (const [packagePath, entry] of Object.entries(toolingLock.packages)) {
  if (!packagePath) {
    continue;
  }
  assert.match(entry.integrity, npmIntegrity, `invalid npm integrity: ${packagePath}`);
  assert.ok(
    entry.resolved.startsWith("https://registry.npmjs.org/"),
    `unresolved npm artifact: ${packagePath}`
  );
  const wordpressMatch = packagePath.match(/node_modules\/(\@wordpress\/[^/]+)$/);
  if (wordpressMatch) {
    const packageName = wordpressMatch[1];
    assert.ok(packageName in exactWordPressPackages, `unexpected ${packageName}`);
    assert.equal(entry.version, exactWordPressPackages[packageName], packageName);
    seenWordPressPackages.add(packageName);
  }
  if (packagePath.endsWith("node_modules/@ariakit/react")) {
    assert.equal(entry.version, "0.4.21", "Ariakit drifted from provider lock");
  }
}
assert.deepEqual(
  [...seenWordPressPackages].sort(),
  Object.keys(exactWordPressPackages).sort(),
  "exact WordPress runtime package closure drifted"
);
assert.equal(
  toolingLock.packages["node_modules/@wordpress/components"].integrity,
  profile.packages.find(({ request }) => request === "@wordpress/components").npm
    .integrity
);
assert.equal(
  toolingLock.packages["node_modules/@wordpress/element"].integrity,
  profile.packages.find(({ request }) => request === "@wordpress/element").npm
    .integrity
);

const generatedMainPath = path.join(workRoot, "sdk032/fixture/Main.tsx");
const generatedMain = fs.readFileSync(generatedMainPath, "utf8");
for (const expectedSource of [
  'from "@wordpress/components"',
  'from "@wordpress/element"',
  "<Button",
  "<Notice",
  "<Main.ProofCheckRow",
  "import('react').MouseEvent<HTMLButtonElement>",
  "import('react').KeyboardEvent<HTMLButtonElement>",
  "import('react').RefObject<HTMLButtonElement>",
  "import('react').Context<string>",
  "import('react').ReactNode[]",
]) {
  assert.ok(generatedMain.includes(expectedSource), `missing ${expectedSource}`);
}
assert.match(
  fs.readFileSync(path.join(workRoot, "sdk032/fixture/ProofStyles.tsx"), "utf8"),
  /prefers-reduced-motion: reduce/
);
for (const forbiddenSource of [
  "genes.react.internal.Jsx",
  ".__jsx",
  ".__frag",
  "HxxParserAdapter",
  "tink.hxx",
]) {
  assert.ok(
    !generatedMain.includes(forbiddenSource),
    `browser output retained ${forbiddenSource}`
  );
}

const mainSourceFile = ts.createSourceFile(
  generatedMainPath,
  generatedMain,
  ts.ScriptTarget.Latest,
  true,
  ts.ScriptKind.TSX
);

function weakKeyword(node) {
  if (node.kind === ts.SyntaxKind.AnyKeyword) {
    return "any";
  }
  if (node.kind === ts.SyntaxKind.UnknownKeyword) {
    return "unknown";
  }
  return null;
}

const publicWeakTypes = [];
function inspectTypeTree(root, label) {
  if (!root) {
    return;
  }
  function visit(node) {
    const weak = weakKeyword(node);
    if (weak) {
      publicWeakTypes.push(`${label}:${weak}`);
    }
    ts.forEachChild(node, visit);
  }
  visit(root);
}
for (const statement of mainSourceFile.statements) {
  if (ts.isClassDeclaration(statement)) {
    for (const member of statement.members) {
      const name = member.name?.getText(mainSourceFile) ?? "constructor";
      inspectTypeTree(member.type, `Main.${name}`);
      for (const parameter of member.parameters ?? []) {
        inspectTypeTree(parameter.type, `Main.${name}.${parameter.name.getText()}`);
      }
    }
  } else if (ts.isTypeAliasDeclaration(statement)) {
    inspectTypeTree(statement.type, statement.name.text);
  }
}
assert.deepEqual(publicWeakTypes, [], "weak type leaked into fixture API");

const internalWeakInventory = [];
function visitInternalWeak(node, owner = "module") {
  let nextOwner = owner;
  if (ts.isMethodDeclaration(node)) {
    nextOwner = `Main.${node.name.getText(mainSourceFile)}`;
  }
  if (ts.isVariableDeclaration(node) && node.type) {
    const isAnyArray =
      ts.isArrayTypeNode(node.type) &&
      node.type.elementType.kind === ts.SyntaxKind.AnyKeyword;
    if (isAnyArray) {
      internalWeakInventory.push(
        `${owner}:${node.name.getText(mainSourceFile)}:any[]`
      );
    }
  }
  ts.forEachChild(node, (child) => visitInternalWeak(child, nextOwner));
}
visitInternalWeak(mainSourceFile);
assert.deepEqual(internalWeakInventory.sort(), [
  "Main.App:tmp:any[]",
  "Main.ProofCheckRow:tmp1:any[]",
  "Main.ProofCheckRow:tmp:any[]",
]);

const generatedMapPath = `${generatedMainPath}.map`;
const generatedMap = readJson(generatedMapPath);
assert.equal(generatedMap.version, 3);
assert.ok(generatedMap.mappings.length > 100, "generated source map is empty");
const fixtureMapSource = generatedMap.sources.find((source) =>
  source?.endsWith("test/hxx-fixture/src/sdk032/fixture/Main.hx")
);
assert.ok(fixtureMapSource, "generated map does not name the Haxe fixture");
assert.equal(
  fs.realpathSync(path.resolve(path.dirname(generatedMapPath), fixtureMapSource)),
  fs.realpathSync(fixtureSource),
  "generated map does not resolve to the Haxe source"
);

function stageNodeModules(root) {
  const target = path.join(root, "node_modules");
  if (!fs.existsSync(target)) {
    fs.symlinkSync(nodeModules, target, "dir");
  }
}

function compilerOptions(root, exactOptionalPropertyTypes, skipLibCheck) {
  return {
    allowSyntheticDefaultImports: true,
    baseUrl: root,
    esModuleInterop: true,
    exactOptionalPropertyTypes,
    jsx: ts.JsxEmit.ReactJSX,
    lib: ["lib.es2022.d.ts", "lib.dom.d.ts", "lib.dom.iterable.d.ts"],
    module: ts.ModuleKind.ESNext,
    moduleResolution: ts.ModuleResolutionKind.Bundler,
    noEmit: true,
    noUncheckedIndexedAccess: true,
    paths: {
      "@sdk032/generated": ["sdk032/fixture/Main.tsx"],
    },
    skipLibCheck,
    strict: true,
    strictNullChecks: true,
    target: ts.ScriptTarget.ES2022,
    typeRoots: [path.join(nodeModules, "@types")],
    types: ["node", "react", "react-dom"],
    verbatimModuleSyntax: true,
  };
}

function formatDiagnostics(diagnostics) {
  const host = {
    getCanonicalFileName: (file) => file,
    getCurrentDirectory: () => workRoot,
    getNewLine: () => "\n",
  };
  return ts.formatDiagnosticsWithColorAndContext(diagnostics, host);
}

function runTypecheck(root, exactOptionalPropertyTypes, skipLibCheck, label) {
  stageNodeModules(root);
  const runtimeEntry = path.join(root, "runtime-entry.tsx");
  const visualEntry = path.join(root, "visual-entry.tsx");
  fs.copyFileSync(runtimeEntrySource, runtimeEntry);
  fs.copyFileSync(visualEntrySource, visualEntry);
  const program = ts.createProgram({
    rootNames: [path.join(root, "index.tsx"), runtimeEntry],
    options: compilerOptions(root, exactOptionalPropertyTypes, skipLibCheck),
  });
  const diagnostics = ts.getPreEmitDiagnostics(program);
  assert.equal(diagnostics.length, 0, `${label}\n${formatDiagnostics(diagnostics)}`);
}

runTypecheck(workRoot, true, true, "generated-source strict typecheck failed");
runTypecheck(
  workRoot,
  false,
  false,
  "provider declaration compatibility typecheck failed"
);

async function buildRuntime(root) {
  const runtimeDirectory = path.join(root, "runtime");
  fs.mkdirSync(runtimeDirectory, { recursive: true });
  const outfile = path.join(runtimeDirectory, "proof.mjs");
  const result = await build({
    absWorkingDir: root,
    alias: {
      "@sdk032/generated": path.join(root, "sdk032/fixture/Main.tsx"),
    },
    bundle: true,
    define: {
      "process.env.NODE_ENV": '"test"',
    },
    entryPoints: [path.join(root, "runtime-entry.tsx")],
    format: "esm",
    jsx: "automatic",
    legalComments: "none",
    logLevel: "silent",
    metafile: true,
    nodePaths: [nodeModules],
    outfile,
    platform: "browser",
    sourcemap: "external",
    sourcesContent: true,
    target: ["es2022"],
    treeShaking: true,
  });
  return { outfile, metafile: result.metafile };
}

async function buildVisual(root) {
  const visualDirectory = path.join(root, "runtime/visual");
  fs.mkdirSync(visualDirectory, { recursive: true });
  const outfile = path.join(visualDirectory, "proof.js");
  const result = await build({
    absWorkingDir: root,
    alias: {
      "@sdk032/generated": path.join(root, "sdk032/fixture/Main.tsx"),
    },
    bundle: true,
    define: {
      "process.env.NODE_ENV": '"production"',
    },
    entryPoints: [path.join(root, "visual-entry.tsx")],
    format: "esm",
    jsx: "automatic",
    legalComments: "none",
    logLevel: "silent",
    metafile: true,
    nodePaths: [nodeModules],
    outfile,
    platform: "browser",
    sourcemap: "external",
    sourcesContent: true,
    target: ["es2022"],
    treeShaking: true,
  });
  return { outfile, metafile: result.metafile };
}

runTypecheck(replayRoot, true, true, "replay strict typecheck failed");
const firstBundle = await buildRuntime(workRoot);
const replayBundle = await buildRuntime(replayRoot);
for (const suffix of ["", ".map"]) {
  assert.deepEqual(
    fs.readFileSync(`${firstBundle.outfile}${suffix}`),
    fs.readFileSync(`${replayBundle.outfile}${suffix}`),
    `runtime bundle${suffix} is nondeterministic`
  );
}
const firstVisualBundle = await buildVisual(workRoot);
const replayVisualBundle = await buildVisual(replayRoot);
for (const relativePath of [
  "proof.js",
  "proof.js.map",
  "proof.css",
  "proof.css.map",
]) {
  assert.deepEqual(
    fs.readFileSync(path.join(path.dirname(firstVisualBundle.outfile), relativePath)),
    fs.readFileSync(path.join(path.dirname(replayVisualBundle.outfile), relativePath)),
    `visual bundle ${relativePath} is nondeterministic`
  );
}

const bundleBytes = fs.readFileSync(firstBundle.outfile);
const bundleText = bundleBytes.toString("utf8");
assert.ok(bundleBytes.length < 4_500_000, "SDK-032 proof bundle exceeded 4.5 MB");
for (const forbiddenRuntime of [
  "HxxParserAdapter",
  "BrowserHxxLowerer",
  "genes.react.internal.Jsx",
  "__jsx(",
  "__frag(",
  "tink_hxx",
]) {
  assert.ok(!bundleText.includes(forbiddenRuntime), `bundle retained ${forbiddenRuntime}`);
}
assertNoMachinePath("runtime bundle", bundleText);

const bundledMap = readJson(`${firstBundle.outfile}.map`);
assert.equal(bundledMap.version, 3);
assert.ok(bundledMap.mappings.length > 100, "bundled source map is empty");
assert.ok(
  bundledMap.sources.some((source) =>
    source.endsWith("test/hxx-fixture/src/sdk032/fixture/Main.hx")
  ),
  "bundled source map does not compose back to Haxe"
);
assertNoMachinePath("runtime source map", JSON.stringify(bundledMap));

const visualBundleBytes = fs.readFileSync(firstVisualBundle.outfile);
const visualBundleText = visualBundleBytes.toString("utf8");
const visualCssPath = path.join(path.dirname(firstVisualBundle.outfile), "proof.css");
const visualCssBytes = fs.readFileSync(visualCssPath);
assert.ok(
  visualBundleBytes.length < 4_500_000,
  "SDK-032 visual bundle exceeded 4.5 MB"
);
assert.ok(
  visualCssBytes.toString("utf8").includes(".components-button"),
  "visual bundle omitted the Gutenberg component styles"
);
assert.ok(
  !visualBundleText.includes("React.createElement"),
  "visual bundle requires an undeclared classic React global"
);
for (const forbiddenRuntime of [
  "HxxParserAdapter",
  "BrowserHxxLowerer",
  "genes.react.internal.Jsx",
  "__jsx(",
  "__frag(",
  "tink_hxx",
]) {
  assert.ok(
    !visualBundleText.includes(forbiddenRuntime),
    `visual bundle retained ${forbiddenRuntime}`
  );
}
assertNoMachinePath("visual bundle", visualBundleText);
const visualBundleMap = readJson(`${firstVisualBundle.outfile}.map`);
assert.ok(
  visualBundleMap.sources.some((source) =>
    source.endsWith("test/hxx-fixture/src/sdk032/fixture/Main.hx")
  ),
  "visual source map does not compose back to Haxe"
);
assertNoMachinePath("visual source map", JSON.stringify(visualBundleMap));

function installDomGlobals(window) {
  for (const name of [
    "CSSStyleSheet",
    "DocumentFragment",
    "Element",
    "Event",
    "HTMLElement",
    "HTMLButtonElement",
    "KeyboardEvent",
    "MouseEvent",
    "MutationObserver",
    "Node",
    "NodeFilter",
    "SVGElement",
  ]) {
    if (name in window) {
      Object.defineProperty(globalThis, name, {
        configurable: true,
        value: window[name],
      });
    }
  }
  Object.defineProperties(globalThis, {
    document: { configurable: true, value: window.document },
    getComputedStyle: { configurable: true, value: window.getComputedStyle.bind(window) },
    navigator: { configurable: true, value: window.navigator },
    window: { configurable: true, value: window },
  });
  const matchMedia = (query) => ({
    addEventListener() {},
    addListener() {},
    dispatchEvent() {
      return true;
    },
    matches: false,
    media: query,
    onchange: null,
    removeEventListener() {},
    removeListener() {},
  });
  class ResizeObserver {
    disconnect() {}
    observe() {}
    unobserve() {}
  }
  class IntersectionObserver extends ResizeObserver {
    takeRecords() {
      return [];
    }
  }
  window.matchMedia = matchMedia;
  window.ResizeObserver = ResizeObserver;
  window.IntersectionObserver = IntersectionObserver;
  Object.defineProperties(globalThis, {
    IntersectionObserver: { configurable: true, value: IntersectionObserver },
    IS_REACT_ACT_ENVIRONMENT: { configurable: true, value: true },
    ResizeObserver: { configurable: true, value: ResizeObserver },
    cancelAnimationFrame: {
      configurable: true,
      value: (handle) => clearTimeout(handle),
    },
    requestAnimationFrame: {
      configurable: true,
      value: (callback) => setTimeout(() => callback(Date.now()), 0),
    },
  });
  window.cancelAnimationFrame = globalThis.cancelAnimationFrame;
  window.requestAnimationFrame = globalThis.requestAnimationFrame;
  window.scrollTo = () => {};
}

const dom = new JSDOM('<!doctype html><html><body><div id="root"></div></body></html>', {
  pretendToBeVisual: true,
  url: "https://wordpresshx.invalid/sdk-032/",
});
installDomGlobals(dom.window);
const consoleErrors = [];
const originalConsoleError = console.error;
console.error = (...values) => {
  consoleErrors.push(values.map(String).join(" "));
};

try {
  const runtime = await import(
    `${pathToFileURL(firstBundle.outfile).href}?sha=${sha256(bundleBytes)}`
  );
  const container = dom.window.document.getElementById("root");
  assert.ok(container);
  await runtime.mount(container);

  const proof = container.querySelector("main.proof");
  assert.ok(proof, "React fixture did not mount");
  assert.equal(proof.getAttribute("data-state"), "review");
  assert.equal(container.querySelectorAll(".proof__check").length, 3);
  assert.equal(
    container.querySelector(".proof__context")?.getAttribute("data-context"),
    "wp70-release / local proof"
  );
  assert.ok(container.querySelector(".components-notice"), "WordPress Notice missing");

  const action = container.querySelector("button.proof__action");
  assert.ok(action instanceof dom.window.HTMLButtonElement, "WordPress Button missing");
  assert.ok(action.classList.contains("components-button"));
  assert.equal(action.getAttribute("data-ref-ready"), "true");
  assert.equal(action.getAttribute("aria-controls"), "proof-result");

  const user = userEvent.setup({ document: dom.window.document });
  const checkButtons = container.querySelectorAll(".proof__check-trigger");
  await runtime.runInAct(() => user.click(checkButtons[1]));
  assert.match(
    container.querySelector(".proof__annotation")?.textContent ?? "",
    /GUTENBERG RUNTIME/
  );
  assert.equal(
    container.querySelectorAll('.proof__check[data-state="selected"]').length,
    1
  );

  await runtime.runInAct(() => user.click(action));
  assert.equal(proof.getAttribute("data-state"), "accepted");
  assert.match(container.querySelector("#proof-result")?.textContent ?? "", /registered/i);
  await runtime.runInAct(() => user.click(action));
  assert.equal(proof.getAttribute("data-state"), "review");

  action.focus();
  assert.equal(dom.window.document.activeElement, action);
  await runtime.runInAct(() => user.keyboard("{Enter}"));
  assert.equal(action.getAttribute("data-key-seen"), "Enter");
  assert.equal(proof.getAttribute("data-state"), "accepted");

  const styles = container.querySelector("style")?.textContent ?? "";
  assert.match(styles, /@media \(prefers-reduced-motion: reduce\)/);
  const axeResult = await axe.run(container, {
    rules: {
      "color-contrast": { enabled: false },
    },
  });
  const seriousViolations = axeResult.violations.filter(({ impact }) =>
    impact === "serious" || impact === "critical"
  );
  assert.deepEqual(
    seriousViolations.map(({ id, impact }) => ({ id, impact })),
    [],
    "serious accessibility violations found"
  );
  assert.deepEqual(consoleErrors, [], "React/Gutenberg emitted console errors");
  await runtime.unmount();

  const evidence = {
    schemaVersion: 1,
    profileId: profile.profileId,
    generatedTreeSha256: sha256(
      Buffer.concat(
        [...relativeTree(workRoot)].flatMap(([name, content]) => [
          Buffer.from(name),
          Buffer.from([0]),
          content,
          Buffer.from([0]),
        ])
      )
    ),
    generatedMainSha256: sha256(generatedMain),
    bundleSha256: sha256(bundleBytes),
    bundleBytes: bundleBytes.length,
    visualBundle: {
      javascriptSha256: sha256(visualBundleBytes),
      javascriptBytes: visualBundleBytes.length,
      cssSha256: sha256(visualCssBytes),
      cssBytes: visualCssBytes.length,
      undeclaredReactGlobal: false,
    },
    publicWeakTypes,
    internalWeakInventory,
    runtime: {
      componentCount: 2,
      context: true,
      event: true,
      keyboard: true,
      ref: true,
      state: true,
    },
    accessibility: {
      engine: `axe-core ${toolingManifest.devDependencies["axe-core"]}`,
      seriousOrCriticalViolations: 0,
      colorContrastExecution: "separate-browser-visual-review",
      reducedMotionRule: true,
    },
    sourceMaps: {
      generatedToHaxe: true,
      bundleToHaxe: true,
      machinePathLeaks: 0,
    },
  };
  fs.writeFileSync(
    path.join(workRoot, "runtime/sdk-032-evidence.json"),
    `${JSON.stringify(evidence, null, 2)}\n`
  );
  fs.writeSync(process.stdout.fd, `${JSON.stringify(evidence, null, 2)}\n`);
} finally {
  console.error = originalConsoleError;
  dom.window.close();
}

// Gutenberg tooltip timers are irrelevant after unmount but keep Node alive.
process.exit(0);
